/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import java.awt.Color;

/**
 *
 * @author Kenneth
 */
public class userConsultas extends javax.swing.JFrame {

    /**
     * Creates new form userConsultas
     */
    public userConsultas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        btnHome = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        kGradientPanel2 = new keeptoo.KGradientPanel();
        mainPanel = new javax.swing.JPanel();
        kButton1 = new keeptoo.KButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        kButton2 = new keeptoo.KButton();
        kButton3 = new keeptoo.KButton();
        kButton4 = new keeptoo.KButton();
        jSeparator1 = new javax.swing.JSeparator();
        txtApellido = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtPassw2 = new javax.swing.JPasswordField();
        txtPassw1 = new javax.swing.JPasswordField();
        jLabel10 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        txtTelefono = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kGradientPanel1.setkEndColor(new java.awt.Color(51, 0, 204));
        kGradientPanel1.setkStartColor(new java.awt.Color(204, 0, 204));
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/home.png"))); // NOI18N
        kGradientPanel1.add(btnHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/newProposal.png"))); // NOI18N
        jLabel8.setText("jLabel8");
        kGradientPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, 60, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/config.png"))); // NOI18N
        kGradientPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 650, -1, -1));

        getContentPane().add(kGradientPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 800));

        kGradientPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mainPanel.setBackground(new Color(0,0,0,80));
        mainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kButton1.setText("kButton1");
        mainPanel.add(kButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 60, 140, -1));

        jLabel2.setBackground(new java.awt.Color(204, 0, 204));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 16));
        jLabel2.setText("Cambiar Nombre");
        mainPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jLabel3.setBackground(new java.awt.Color(204, 0, 204));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 16));
        jLabel3.setText("Cambiar Datos de Contacto");
        mainPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        kButton2.setText("kButton2");
        mainPanel.add(kButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 530, 140, -1));

        kButton3.setText("kButton2");
        mainPanel.add(kButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 230, 140, -1));

        kButton4.setText("kButton2");
        mainPanel.add(kButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 380, 140, -1));
        mainPanel.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 490, 940, 10));

        txtApellido.setFont(new java.awt.Font("Segoe UI", 0, 14));
        txtApellido.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtApellido.setPreferredSize(new java.awt.Dimension(70, 30));
        mainPanel.add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, 330, 40));

        txtNombre.setFont(new java.awt.Font("Segoe UI", 0, 14));
        txtNombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNombre.setPreferredSize(new java.awt.Dimension(70, 30));
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        mainPanel.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 40, 330, 40));
        mainPanel.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 940, 10));
        mainPanel.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 940, 10));

        jLabel4.setBackground(new java.awt.Color(51, 51, 255));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Nombre");
        mainPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, -1, -1));

        jLabel5.setBackground(new java.awt.Color(51, 51, 255));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14));
        jLabel5.setText("Apellido");
        mainPanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, -1, -1));

        jLabel7.setBackground(new java.awt.Color(204, 0, 204));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 16));
        jLabel7.setText("Cambiar Contraseña");
        mainPanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, -1, -1));

        txtPassw2.setFont(new java.awt.Font("Segoe UI", 0, 14));
        txtPassw2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPassw2.setPreferredSize(new java.awt.Dimension(70, 30));
        mainPanel.add(txtPassw2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 430, 330, 40));

        txtPassw1.setFont(new java.awt.Font("Segoe UI", 0, 14));
        txtPassw1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPassw1.setPreferredSize(new java.awt.Dimension(70, 30));
        mainPanel.add(txtPassw1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 370, 330, 40));

        jLabel10.setBackground(new java.awt.Color(204, 0, 204));
        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 16));
        jLabel10.setText("Borrar Propuesta");
        mainPanel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 510, -1, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.setMinimumSize(new java.awt.Dimension(70, 30));
        jComboBox1.setPreferredSize(new java.awt.Dimension(70, 30));
        mainPanel.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 540, 330, 50));

        txtTelefono.setFont(new java.awt.Font("Segoe UI", 0, 14));
        txtTelefono.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTelefono.setPreferredSize(new java.awt.Dimension(70, 30));
        mainPanel.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 280, 330, 40));

        txtCorreo.setFont(new java.awt.Font("Segoe UI", 0, 14));
        txtCorreo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCorreo.setPreferredSize(new java.awt.Dimension(70, 30));
        txtCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCorreoActionPerformed(evt);
            }
        });
        mainPanel.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 210, 330, 40));

        jLabel11.setBackground(new java.awt.Color(51, 51, 255));
        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14));
        jLabel11.setText("Correo");
        mainPanel.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, -1, -1));

        jLabel12.setBackground(new java.awt.Color(51, 51, 255));
        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14));
        jLabel12.setText("Telefono");
        mainPanel.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, -1, -1));

        jLabel14.setBackground(new java.awt.Color(51, 51, 255));
        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14));
        jLabel14.setText("Nueva Contraseña");
        mainPanel.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 380, -1, -1));

        jLabel15.setBackground(new java.awt.Color(51, 51, 255));
        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 14));
        jLabel15.setText("Propuesta a borrar");
        mainPanel.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 550, -1, -1));

        jLabel16.setBackground(new java.awt.Color(51, 51, 255));
        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 14));
        jLabel16.setText("Nueva Contraseña");
        mainPanel.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 440, -1, -1));

        kGradientPanel2.add(mainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 940, 630));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cancel36px.png"))); // NOI18N
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        kGradientPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 10, -1, 40));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("Ajustes");
        kGradientPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 60, -1, 50));

        getContentPane().add(kGradientPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 980, 800));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel6MouseClicked

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorreoActionPerformed

    private void  configHelper(int opc){
        mainPanel.removeAll();
        mainPanel.repaint();
        switch(opc){
            case 1:
                javax.swing.JLabel lblNombre =new javax.swing.JLabel();
                javax.swing.JTextField txtNombre = new javax.swing.JTextField();
                lblNombre.setText("Ingrese el nombre ");
                lblNombre.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
                lblNombre.setForeground(new java.awt.Color(255, 0, 204));
                txtNombre.setFont(new java.awt.Font("Segoe UI", 1, 14));
                
               mainPanel.add(lblNombre,new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 200, -1,-1));
               mainPanel.add(txtNombre,new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 400, 100,-1));
               pack();
               break;
            
            case 2:
                javax.swing.JLabel lblPassw =new javax.swing.JLabel();
                javax.swing.JPasswordField txtPassw = new javax.swing.JPasswordField();
                javax.swing.JPasswordField txtPassw2 = new javax.swing.JPasswordField();
                lblPassw.setText("Cambiar Contraseña ");
                lblPassw.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
                lblPassw.setForeground(new java.awt.Color(255, 0, 204));
               
                txtPassw.setFont(new java.awt.Font("Segoe UI", 1, 14));
                txtPassw2.setFont(new java.awt.Font("Segoe UI", 1, 14));
               mainPanel.add(lblPassw,new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 35, -1,-1));
               mainPanel.add(txtPassw,new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 35, -1,-1));
               mainPanel.add(txtPassw2,new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 35, -1,-1));
               pack();
               break;
                
            case 3:
                javax.swing.JLabel lblProposal =new javax.swing.JLabel();
                javax.swing.JComboBox<String> cbxTitulos = new javax.swing.JComboBox<String>();
                cbxTitulos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
                lblProposal.setText("Escoja la propuesta que desea borrar ");
                lblProposal.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
                mainPanel.add(lblProposal,new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 35, -1,-1));
                mainPanel.add(cbxTitulos,new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 35, -1,-1));
                pack();
               break;
                
            case 4:
                javax.swing.JLabel lblTelefono =new javax.swing.JLabel();
                javax.swing.JLabel lblCorreo=new javax.swing.JLabel();
                lblTelefono.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
                lblTelefono.setForeground(new java.awt.Color(255, 0, 204));
                lblTelefono.setText("Ingrese el Nuevo Telefono");
                lblCorreo.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
                lblCorreo.setForeground(new java.awt.Color(255, 0, 204));
                lblCorreo.setText("Ingrese el Nuevo Correo");
                javax.swing.JTextField txtCorreo = new javax.swing.JTextField();
                javax.swing.JTextField txtTelefono = new javax.swing.JTextField();
                txtCorreo.setFont(new java.awt.Font("Segoe UI", 1, 14));
                txtTelefono.setFont(new java.awt.Font("Segoe UI", 1, 14));
                mainPanel.add(lblTelefono,new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 35, -1,-1));
                mainPanel.add(lblCorreo,new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 35, -1,-1));
               pack();
               break;

                
                
                
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(userConsultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(userConsultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(userConsultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(userConsultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new userConsultas().setVisible(true);
            }
        });
    }
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnHome;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private keeptoo.KButton kButton1;
    private keeptoo.KButton kButton2;
    private keeptoo.KButton kButton3;
    private keeptoo.KButton kButton4;
    private keeptoo.KGradientPanel kGradientPanel1;
    private keeptoo.KGradientPanel kGradientPanel2;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JPasswordField txtPassw1;
    private javax.swing.JPasswordField txtPassw2;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
