ALTER Table BINNACLE
ADD Constraint fk_BINNACLE_PERSON 
FOREIGN Key (ID_PERSON) REFERENCES PERSON(ID_PERSON);

ALTER Table PERSON
ADD Constraint fk_PERSON_COMMUNITY
FOREIGN Key (ID_COMMUNITY) REFERENCES Community(ID_COMMUNITY);

ALTER Table COMMUNITY
ADD Constraint fk_COMMUNITY_DISTRICT
FOREIGN Key (ID_DISTRICT) REFERENCES DISTRICT(ID_DISTRICT);

ALTER Table DISTRICT
ADD Constraint fk_DISTRICT_CANTON
FOREIGN Key (ID_CANTON) REFERENCES CANTON(ID_CANTON);

ALTER Table CANTON
ADD Constraint fk_CANTON_PROVINCE 
FOREIGN Key (ID_PROVINCE) REFERENCES PROVINCE(ID_PROVINCE);

ALTER Table PROVINCE
ADD Constraint fk_PROVINCE_COUNTRY
FOREIGN Key (ID_COUNTRY) REFERENCES COUNTRY(ID_COUNTRY);

ALTER Table USERNAME
ADD Constraint fk_USERNAME_PERSON
FOREIGN Key (ID_PERSON) REFERENCES PERSON(ID_PERSON);

ALTER Table EMAIL
ADD Constraint fk_EMAIL_PERSON
FOREIGN Key (ID_PERSON) REFERENCES PERSON(ID_PERSON);

ALTER Table TELEPHONE
ADD Constraint fk_TELEPHONE_PERSON
FOREIGN Key (ID_PERSON) REFERENCES PERSON(ID_PERSON);

ALTER Table NATIONALITY_X_PERSON
ADD Constraint fk_NATIONALITY_PERSON
FOREIGN Key (ID_PERSON) REFERENCES PERSON(ID_PERSON);
ALTER Table NATIONALITY_X_PERSON
ADD Constraint fk_NATIONALITY_NATIONALITY
FOREIGN Key (ID_NATIONALITY) REFERENCES NATIONALITY(ID_NATIONALITY);
/*
ALTER Table KIND_PERSON
ADD Constraint fk_KIND_PERSON_PERSON
FOREIGN Key (ID_PERSON) REFERENCES PERSON(ID_PERSON);
*/

ALTER Table CATEGORY_X_PERSON
ADD Constraint fk_CATEGORY_PERSON
FOREIGN Key (ID_PERSON) REFERENCES PERSON(ID_PERSON);
ALTER Table CATEGORY_X_PERSON
ADD Constraint fk_CATEGORY_CATEGORY
FOREIGN Key (ID_CATEGORY) REFERENCES CATEGORY_FAV(ID_CATEGORY_FAV);

ALTER Table PROPOSAL_X_CATEGORY
ADD Constraint fk_PROPOSAL_CATEGORY
FOREIGN Key (ID_PROPOSAL) REFERENCES PROPOSAL(ID_PROPOSAL);
ALTER Table PROPOSAL_X_CATEGORY
ADD Constraint fk_CATEGORY_ID_CATEGORY
FOREIGN Key (ID_CATEGORY_FAV) REFERENCES CATEGORY_FAV(ID_CATEGORY_FAV);

ALTER Table VOTE
ADD Constraint fk_VOTE_PERSON
FOREIGN Key (ID_PERSON) REFERENCES PERSON(ID_PERSON);
ALTER Table VOTE
ADD Constraint fk_VOTE_PROPOSAL
FOREIGN Key (ID_PROPOSAL) REFERENCES PROPOSAL(ID_PROPOSAL);

ALTER Table PERSON_X_PROPOSAL
ADD Constraint fk_PROPOSAL_PERSON
FOREIGN Key (ID_PERSON) REFERENCES PERSON(ID_PERSON);
ALTER Table PERSON_X_PROPOSAL
ADD Constraint fk_PROPOSAL_PROPOSAL
FOREIGN Key (ID_PROPOSAL) REFERENCES PROPOSAL(ID_PROPOSAL);

ALTER Table PERSON_X_COMMENT
ADD Constraint fk_COMMENT_PERSON
FOREIGN Key (ID_PERSON) REFERENCES PERSON(ID_PERSON);
ALTER Table PERSON_X_COMMENT
ADD Constraint fk_COMMENT_COMMENT
FOREIGN Key (ID_COMMENT) REFERENCES COMMENT_PROP(ID_COMMENT);

ALTER Table PROPORSAL_X_COMMENT
ADD Constraint fk_COMMENT_PROPOSAL
FOREIGN Key (ID_COMMENT) REFERENCES COMMENT_PROP(ID_COMMENT);
ALTER Table PROPORSAL_X_COMMENT
ADD Constraint fk_PROPOSAL_ID_PROPOSAL
FOREIGN Key (ID_PROPORSAL) REFERENCES PROPOSAL(ID_PROPOSAL);
