CREATE OR REPLACE PACKAGE PKG_ADMIN_PERSON  IS
       PROCEDURE PROC_INSERT_PERSON(ID_PERSON NUMBER,ID_COMMUNITY NUMBER,NAME_PERSON VARCHAR2,
         FIRST_LAST_NAME VARCHAR2,BIRTHDATE DATE, SECOND_LAST_NAME VARCHAR2);
END PKG_ADMIN_PERSON;

CREATE OR REPLACE PACKAGE BODY PKG_ADMIN_PERSON IS
       PROCEDURE PROC_INSERT_PERSON(ID_PERSON NUMBER,ID_COMMUNITY NUMBER,NAME_PERSON VARCHAR2,
                 FIRST_LAST_NAME VARCHAR2,BIRTHDATE DATE, SECOND_LAST_NAME VARCHAR2) IS
         
           BEGIN
             INSERT INTO PERSON(ID_PERSON,ID_COMMUNITY,NAME_PERSON,FIRST_LAST_NAME, BIRTHDATE,SECOND_LAST_NAME)
             VALUES (ID_PERSON,ID_COMMUNITY,NAME_PERSON,FIRST_LAST_NAME, BIRTHDATE,SECOND_LAST_NAME);
             
           END;
       
END PKG_ADMIN_PERSON;

-----------------------------------------------------------------------------------------------

CREATE OR REPLACE PACKAGE PKG_ADMIN_BINNACLE  IS
       PROCEDURE PROC_INSERT_BINNACLE(ID_BINNACLE NUMBER,ID_PERSON NUMBER ,DATE_CHANGE DATA ,PASSWORD_USER_BIN VARCHAR2);
END PKG_ADMIN_BINNACLE;

CREATE OR REPLACE PACKAGE BODY PKG_ADMIN_BINNACLE IS
       PROCEDURE PROC_INSERT_BINNACLE(ID_BINNACLE NUMBER,ID_PERSON NUMBER ,DATE_CHANGE DATA ,PASSWORD_USER_BIN VARCHAR2) IS
         
           BEGIN
             INSERT INTO BINNACLE(ID_BINNACLE,ID_PERSON,DATE_CHANGE,PASSWORD_USER_BIN)
             VALUES (ID_BINNACLE,ID_PERSON,DATE_CHANGE,PASSWORD_USER_BIN);
             
           END;
       
END PKG_ADMIN_BINNACLE;

-----------------------------------------------------------------------------------------------

CREATE OR REPLACE PACKAGE PKG_ADMIN_CANTON  IS
       PROCEDURE PROC_INSERT_CANTON(ID_CANTON NUMBER,ID_PROVINCE NUMBER ,NAME_CANTON VARCHAR2);
END PKG_ADMIN_CANTON;

CREATE OR REPLACE PACKAGE BODY PKG_ADMIN_CANTON IS
       PROCEDURE PROC_INSERT_CANTON(ID_CANTON NUMBER,ID_PROVINCE NUMBER ,NAME_CANTON VARCHAR2) IS
         
           BEGIN
             INSERT INTO CANTON(ID_CANTON,ID_PROVINCE,NAME_CANTON)
             VALUES (ID_CANTON,ID_PROVINCE,NAME_CANTON);
             
           END;
       
END PKG_ADMIN_CANTON;

-----------------------------------------------------------------------------------------------

CREATE OR REPLACE PACKAGE PKG_ADMIN_CATEGORY_FAV  IS
       PROCEDURE PROC_INSERT_CATEGORY_FAV(ID_CATEGORY_FAV NUMBER, NAME_CATEGORY VARCHAR2);
END PKG_ADMIN_CATEGORY_FAV;

CREATE OR REPLACE PACKAGE BODY PKG_ADMIN_CATEGORY_FAV IS
       PROCEDURE PROC_INSERT_CATEGORY_FAV(ID_CATEGORY_FAV NUMBER, NAME_CATEGORY VARCHAR2) IS
         
           BEGIN
             INSERT INTO CATEGORY_FAV(ID_CATEGORY_FAV, NAME_CATEGORY)
             VALUES (ID_CATEGORY_FAV, NAME_CATEGORY);
             
           END;
       
END PKG_ADMIN_CATEGORY_FAV;

-----------------------------------------------------------------------------------------------


CREATE OR REPLACE PACKAGE PKG_ADMIN_CATEGORY_X_PERSON  IS
       PROCEDURE PROC_INSERT_CATEGORY_X_PERSON(ID_PERSON NUMBER, ID_CATEGORY NUMBER);
END PKG_ADMIN_CATEGORY_X_PERSON;

CREATE OR REPLACE PACKAGE BODY PKG_ADMIN_CATEGORY_X_PERSON IS
       PROCEDURE PROC_INSERT_CATEGORY_X_PERSON(ID_PERSON NUMBER, ID_CATEGORY NUMBER) IS
         
           BEGIN
             INSERT INTO CATEGORY_X_PERSON(ID_PERSON, ID_CATEGORY)
             VALUES (ID_PERSON, ID_CATEGORY);
             
           END;
       
END PKG_ADMIN_CATEGORY_X_PERSON;

-----------------------------------------------------------------------------------------------

CREATE OR REPLACE PACKAGE PKG_ADMIN_COMMENT_PROP  IS
       PROCEDURE PROC_INSERT_COMMENT_PROP(ID_COMMENT NUMBER,DESCRIPTION_COMMENT VARCHAR2,DATE_COMMENT DATE);
END PKG_ADMIN_COMMENT_PROP;

CREATE OR REPLACE PACKAGE BODY PKG_ADMIN_COMMENT_PROP IS
       PROCEDURE PROC_INSERT_COMMENT_PROP(ID_COMMENT NUMBER,DESCRIPTION_COMMENT VARCHAR2,DATE_COMMENT DATE) IS
         
           BEGIN
             INSERT INTO COMMENT_PROP(ID_COMMENT,DESCRIPTION_COMMENT,DATE_COMMENT)
             VALUES (ID_COMMENT,DESCRIPTION_COMMENT,DATE_COMMENT);
             
           END;
       
END PKG_ADMIN_COMMENT_PROP;

-----------------------------------------------------------------------------------------------

CREATE OR REPLACE PACKAGE PKG_ADMIN_COMMUNITY  IS
       PROCEDURE PROC_INSERT_COMMUNITY(ID_COMMUNITY NUMBER,ID_DISTRICT NUMBER,NAME_COMMUNITY VARCHAR2);
END PKG_ADMIN_COMMUNITY;

CREATE OR REPLACE PACKAGE BODY PKG_ADMIN_COMMUNITY IS
       PROCEDURE PROC_INSERT_COMMUNITY(ID_COMMUNITY NUMBER,ID_DISTRICT NUMBER,NAME_COMMUNITY VARCHAR2) IS
         
           BEGIN
             INSERT INTO COMMUNITY(ID_COMMUNITY,ID_DISTRICT,NAME_COMMUNITY)
             VALUES (ID_COMMUNITY,ID_DISTRICT,NAME_COMMUNITY);
             
           END;
       
END PKG_ADMIN_COMMUNITY;

-----------------------------------------------------------------------------------------------

CREATE OR REPLACE PACKAGE PKG_ADMIN_COUNTRY  IS
       PROCEDURE PROC_INSERT_COUNTRY(ID_COUNTRY NUMBER, NAME_COUNTRY VARCHAR2);
END PKG_ADMIN_COUNTRY;

CREATE OR REPLACE PACKAGE BODY PKG_ADMIN_COUNTRY IS
       PROCEDURE PROC_INSERT_COUNTRY(ID_COUNTRY NUMBER, NAME_COUNTRY VARCHAR2) IS
         
           BEGIN
             INSERT INTO COUNTRY(ID_COUNTRY, NAME_COUNTRY)
             VALUES (ID_COUNTRY, NAME_COUNTRY);
             
           END;
       
END PKG_ADMIN_COUNTRY;

-----------------------------------------------------------------------------------------------

CREATE OR REPLACE PACKAGE PKG_ADMIN_DISTRICT  IS
       PROCEDURE PROC_INSERT_DISTRICT(ID_DISTRICT NUMBER,ID_CANTON NUMBER,NAME_DISTRICT VARCHAR2);
END PKG_ADMIN_DISTRICT;

CREATE OR REPLACE PACKAGE BODY PKG_ADMIN_DISTRICT IS
       PROCEDURE PROC_INSERT_DISTRICT(ID_DISTRICT NUMBER,ID_CANTON NUMBER,NAME_DISTRICT VARCHAR2) IS
         
           BEGIN
             INSERT INTO DISTRICT(ID_DISTRICT,ID_CANTON,NAME_DISTRICT)
             VALUES (ID_DISTRICT,ID_CANTON,NAME_DISTRICT);
             
           END;
       
END PKG_ADMIN_DISTRICT;

-----------------------------------------------------------------------------------------------

CREATE OR REPLACE PACKAGE PKG_ADMIN_EMAIL  IS
       PROCEDURE PROC_INSERT_EMAIL(ID_EMAIL NUMBER,MAIL VARCHAR2,ID_PERSON NUMBER);
END PKG_ADMIN_EMAIL;

CREATE OR REPLACE PACKAGE BODY PKG_ADMIN_EMAIL IS
       PROCEDURE PROC_INSERT_EMAIL(ID_EMAIL NUMBER,MAIL VARCHAR2,ID_PERSON NUMBER) IS
         
           BEGIN
             INSERT INTO EMAIL(ID_EMAIL,MAIL,ID_PERSON)
             VALUES (ID_EMAIL,MAIL,ID_PERSON);
             
           END;
       
END PKG_ADMIN_EMAIL;

-----------------------------------------------------------------------------------------------

CREATE OR REPLACE PACKAGE PKG_ADMIN_KIND_PERSON  IS
       PROCEDURE PROC_INSERT_KIND_PERSON(ID_KIND_PERSON NUMBER,ID_PERSON NUMBER,TITLE_PERSON VARCHAR2);
END PKG_ADMIN_KIND_PERSON;

CREATE OR REPLACE PACKAGE BODY PKG_ADMIN_KIND_PERSON IS
       PROCEDURE PROC_INSERT_KIND_PERSON(ID_KIND_PERSON NUMBER,ID_PERSON NUMBER,TITLE_PERSON VARCHAR2) IS
         
           BEGIN
             INSERT INTO KIND_PERSON(ID_KIND_PERSON,ID_PERSON,TITLE_PERSON)
             VALUES (ID_KIND_PERSON,ID_PERSON,TITLE_PERSON);
             
           END;
       
END PKG_ADMIN_KIND_PERSON;

-----------------------------------------------------------------------------------------------

CREATE OR REPLACE PACKAGE PKG_ADMIN_NATIONALITY  IS
       PROCEDURE PROC_INSERT_NATIONALITY(ID_NATIONALITY NUMBER, NAME_NATIONALITY VARCHAR2);
END PKG_ADMIN_NATIONALITY;

CREATE OR REPLACE PACKAGE BODY PKG_ADMIN_NATIONALITY IS
       PROCEDURE PROC_INSERT_NATIONALITY(ID_NATIONALITY NUMBER, NAME_NATIONALITY VARCHAR2) IS
         
           BEGIN
             INSERT INTO NATIONALITY(ID_NATIONALITY, NAME_NATIONALITY)
             VALUES (ID_NATIONALITY, NAME_NATIONALITY);
             
           END;
       
END PKG_ADMIN_NATIONALITY;

-----------------------------------------------------------------------------------------------

CREATE OR REPLACE PACKAGE PKG_ADMIN_NATIONALITY_X_PERSON  IS
       PROCEDURE PROC_INSERT_NATIONALITY_X_PERSON(ID_NATIONALITY NUMBER, ID_PERSON NUMBER);
END PKG_ADMIN_NATIONALITY_X_PERSON;

CREATE OR REPLACE PACKAGE BODY PKG_ADMIN_NATIONALITY_X_PERSON IS
       PROCEDURE PROC_INSERT_NATIONALITY_X_PERSON(ID_NATIONALITY NUMBER, ID_PERSON NUMBER) IS
         
           BEGIN
             INSERT INTO NATIONALITY_X_PERSON(ID_NATIONALITY, ID_PERSON)
             VALUES (ID_NATIONALITY, ID_PERSON);
             
           END;
       
END PKG_ADMIN_NATIONALITY_X_PERSON;

-----------------------------------------------------------------------------------------------

CREATE OR REPLACE PACKAGE PKG_ADMIN_PARAMETER  IS
       PROCEDURE PROC_INSERT_PARAMETER(ID_PARAMETER NUMBER,NAME_PARAMETER VARCHAR2,VALUE_PARAMETER VARCHAR2);
END PKG_ADMIN_PARAMETER;

CREATE OR REPLACE PACKAGE BODY PKG_ADMIN_PARAMETER IS
       PROCEDURE PROC_INSERT_PARAMETER(ID_PARAMETER NUMBER,NAME_PARAMETER VARCHAR2,VALUE_PARAMETER VARCHAR2) IS
         
           BEGIN
             INSERT INTO PARAMETER(ID_PARAMETER,NAME_PARAMETER,VALUE_PARAMETER)
             VALUES (ID_PARAMETER,NAME_PARAMETER,VALUE_PARAMETER);
             
           END;
       
END PKG_ADMIN_PARAMETER;

-----------------------------------------------------------------------------------------------

CREATE OR REPLACE PACKAGE PKG_ADMIN_PERSON_X_COMMENT  IS
       PROCEDURE PROC_INSERT_PERSON_X_COMMENT(ID_COMMENT NUMBER, ID_PERSON NUMBER);
END PKG_ADMIN_PERSON_X_COMMENT;

CREATE OR REPLACE PACKAGE BODY PKG_ADMIN_PERSON_X_COMMENT IS
       PROCEDURE PROC_INSERT_PERSON_X_COMMENT(ID_COMMENT NUMBER, ID_PERSON NUMBER) IS
         
           BEGIN
             INSERT INTO PERSON_X_COMMENT(ID_COMMENT, ID_PERSON)
             VALUES (ID_COMMENT, ID_PERSON);
             
           END;
       
END PKG_ADMIN_PERSON_X_COMMENT;

-----------------------------------------------------------------------------------------------

CREATE OR REPLACE PACKAGE PKG_ADMIN_PERSON_X_PROPOSAL  IS
       PROCEDURE PROC_INSERT_PERSON_X_PROPOSAL(ID_PROPOSAL NUMBER, ID_PERSON NUMBER);
END PKG_ADMIN_PERSON_X_PROPOSAL;

CREATE OR REPLACE PACKAGE BODY PKG_ADMIN_PERSON_X_PROPOSAL IS
       PROCEDURE PROC_INSERT_PERSON_X_PROPOSAL(ID_PROPOSAL NUMBER, ID_PERSON NUMBER) IS
         
           BEGIN
             INSERT INTO PERSON_X_PROPOSAL(ID_PROPOSAL, ID_PERSON)
             VALUES (ID_PROPOSAL, ID_PERSON);
             
           END;
       
END PKG_ADMIN_PERSON_X_PROPOSAL;

-----------------------------------------------------------------------------------------------

CREATE OR REPLACE PACKAGE PKG_ADMIN_PROPORSAL_X_COMMENT  IS
       PROCEDURE PROC_INSERT_PROPORSAL_X_COMMENT(ID_PROPOSAL NUMBER, ID_COMMENT NUMBER);
END PKG_ADMIN_PROPORSAL_X_COMMENT;

CREATE OR REPLACE PACKAGE BODY PKG_ADMIN_PROPORSAL_X_COMMENT IS
       PROCEDURE PROC_INSERT_PROPORSAL_X_COMMENT(ID_PROPOSAL NUMBER, ID_COMMENT NUMBER) IS
         
           BEGIN
             INSERT INTO PROPORSAL_X_COMMENT(ID_PROPORSAL, ID_COMMENT)
             VALUES (ID_PROPORSAL, ID_COMMENT);
             
           END;
       
END PKG_ADMIN_PROPORSAL_X_COMMENT;

-----------------------------------------------------------------------------------------------

CREATE OR REPLACE PACKAGE PKG_ADMIN_PROPOSAL  IS
       PROCEDURE PROC_INSERT_PROPOSAL(ID_PROPOSAL NUMBER,TITLE VARCHAR2 ,DESCRIPTION_PROPOSAL VARCHAR2,
         BUDGET NUMBER,VOTE NUMBER,DATE_PROPOSAL DATE);
END PKG_ADMIN_PROPOSAL;

CREATE OR REPLACE PACKAGE BODY PKG_ADMIN_PROPOSAL IS
       PROCEDURE PROC_INSERT_PROPOSAL(ID_PROPOSAL NUMBER,TITLE VARCHAR2 ,DESCRIPTION_PROPOSAL VARCHAR2,
         BUDGET NUMBER,VOTE NUMBER,DATE_PROPOSAL DATE) IS
         
           BEGIN
             INSERT INTO PROPOSAL(ID_PROPOSAL,TITLE,DESCRIPTION_PROPOSAL,BUDGET,VOTE,DATE_PROPOSAL)
             VALUES (ID_PROPOSAL,TITLE,DESCRIPTION_PROPOSAL,BUDGET,VOTE,DATE_PROPOSAL);
             
           END;
       
END PKG_ADMIN_PROPOSAL;

-----------------------------------------------------------------------------------------------

CREATE OR REPLACE PACKAGE PKG_ADMIN_PROPOSAL_X_CATEGORY  IS
       PROCEDURE PROC_INSERT_PROPOSAL_X_CATEGORY(ID_PROPOSAL NUMBER, ID_CATEGORY_FAV NUMBER);
END PKG_ADMIN_PROPOSAL_X_CATEGORY;

CREATE OR REPLACE PACKAGE BODY PKG_ADMIN_PROPOSAL_X_CATEGORY IS
       PROCEDURE PROC_INSERT_PROPOSAL_X_CATEGORY(ID_PROPOSAL NUMBER, ID_CATEGORY_FAV NUMBER) IS
         
           BEGIN
             INSERT INTO PROPOSAL_X_CATEGORY(ID_PROPORSAL, ID_CATEGORY_FAV)
             VALUES (ID_PROPORSAL, ID_CATEGORY_FAV);
             
           END;
       
END PKG_ADMIN_PROPOSAL_X_CATEGORY;

-----------------------------------------------------------------------------------------------

CREATE OR REPLACE PACKAGE PKG_ADMIN_PROVINCE  IS
       PROCEDURE PROC_INSERT_PROVINCE(ID_PROVINCE NUMBER,ID_COUNTRY NUMBER,NAME_PROVINCE VARCHAR2);
END PKG_ADMIN_PROVINCE;

CREATE OR REPLACE PACKAGE BODY PKG_ADMIN_PROVINCE IS
       PROCEDURE PROC_INSERT_PROVINCE(ID_PROVINCE NUMBER,ID_COUNTRY NUMBER,NAME_PROVINCE VARCHAR2) IS
         
           BEGIN
             INSERT INTO PROVINCE(ID_PROVINCE,ID_COUNTRY,NAME_PROVINCE)
             VALUES (ID_PROVINCE,ID_COUNTRY,NAME_PROVINCE);
             
           END;
       
END PKG_ADMIN_PROVINCE;

-----------------------------------------------------------------------------------------------

CREATE OR REPLACE PACKAGE PKG_ADMIN_TELEPHONE  IS
       PROCEDURE PROC_INSERT_TELEPHONE(ID_PERSON NUMBER, PHONE_NUMBER NUMBER);
END PKG_ADMIN_TELEPHONE;

CREATE OR REPLACE PACKAGE BODY PKG_ADMIN_TELEPHONE IS
       PROCEDURE PROC_INSERT_TELEPHONE(ID_PERSON NUMBER, PHONE_NUMBER NUMBER) IS
         
           BEGIN
             INSERT INTO TELEPHONE(ID_PERSON, PHONE_NUMBER)
             VALUES (ID_PERSON, PHONE_NUMBER);
             
           END;
       
END PKG_ADMIN_TELEPHONE;

-----------------------------------------------------------------------------------------------

CREATE OR REPLACE PACKAGE PKG_ADMIN_USERNAME  IS
       PROCEDURE PROC_INSERT_USERNAME(ID_USERNAME NUMBER,ID_PERSON NUMBER,PASSWORD_USER VARCHAR2);
END PKG_ADMIN_USERNAME;

CREATE OR REPLACE PACKAGE BODY PKG_ADMIN_USERNAME IS
       PROCEDURE PROC_INSERT_USERNAME(ID_USERNAME NUMBER,ID_PERSON NUMBER,PASSWORD_USER VARCHAR2) IS
         
           BEGIN
             INSERT INTO USERNAME(ID_USERNAME,ID_PERSON,PASSWORD_USER)
             VALUES (ID_USERNAME,ID_PERSON,PASSWORD_USER);
             
           END;
       
END PKG_ADMIN_USERNAME;

-----------------------------------------------------------------------------------------------

CREATE OR REPLACE PACKAGE PKG_ADMIN_VOTE  IS
       PROCEDURE PROC_INSERT_VOTE(ID_PROPOSAL NUMBER, ID_PERSON NUMBER);
END PKG_ADMIN_VOTE;

CREATE OR REPLACE PACKAGE BODY PKG_ADMIN_VOTE IS
       PROCEDURE PROC_INSERT_VOTE(ID_PROPOSAL NUMBER, ID_PERSON NUMBER) IS
         
           BEGIN
             INSERT INTO VOTE(ID_PROPOSAL, ID_PERSON)
             VALUES (ID_PROPOSAL, ID_PERSON);
             
           END;
       
END PKG_ADMIN_VOTE;
