CREATE TABLE PERSON(
       ID_PERSON      NUMBER(9),
       ID_COMMUNITY   NUMBER(5),
       NAME_PERSON    VARCHAR2(20) CONSTRAINT PERSON_NAME_PERSON_NN NOT NULL,
       LAST_NAME      VARCHAR2(25) CONSTRAINT PERSON_LAST_NAME_NN NOT NULL,
       BIRTHDATE      date default sysdate
         
);

CREATE TABLE COMMUNITY(
       ID_COMMUNITY   NUMBER(5),
       ID_DISTRICT    NUMBER(5),
       NAME_COMMUNITY VARCHAR2(25) CONSTRAINT COMMUNITY_NAME_COMMUNITY_NN NOT NULL
);

CREATE TABLE DISTRICT(
       ID_DISTRICT    NUMBER(5),
       ID_CANTON      NUMBER(5),
       NAME_DISTRICT  VARCHAR2(25) CONSTRAINT DISTRICT_NAME_DISTRICT_NN NOT NULL
);

CREATE TABLE CANTON(
       ID_CANTON      NUMBER(5),
       ID_PROVINCE    NUMBER(5),
       NAME_CANTON    VARCHAR2(25) CONSTRAINT CANTON_NAME_CANTON_NN NOT NULL
);

CREATE TABLE PROVINCE(
       ID_PROVINCE      NUMBER(5),
       ID_COUNTRY       NUMBER(5),
       NAME_PROVINCE    VARCHAR2(25) CONSTRAINT PROVINCE_NAME_PROVINCE_NN NOT NULL
);

CREATE TABLE COUNTRY(
       ID_COUNTRY       NUMBER(5),
       NAME_COUNTRY     VARCHAR2(25) CONSTRAINT COUNTRY_NAME_COUNTRY_NN NOT NULL
);

CREATE TABLE USERNAME(
       ID_USERNAME      NUMBER(5),
       ID_PERSON        NUMBER(5)
);

CREATE TABLE EMAIL(
       ID_EMAIL         NUMBER(5),
       MAIL             VARCHAR2(25) constraint EMAIL_MAIL_PERSON_NN not null, constraint EMAIL_MAIL_PERSON_UK unique(MAIL),
       ID_PERSON        NUMBER(5)       
);

CREATE TABLE TELEPHONE(
       ID_PERSON        NUMBER(5),
       PHONE_NUMBER     NUMBER(8)
);

CREATE TABLE NATIONALITY_X_PERSON(
       ID_NATIONALITY   NUMBER(5),
       ID_PERSON        NUMBER(5)
);

CREATE TABLE NATIONALITY(
       ID_NATIONALITY   NUMBER(5),
       NAME_NATIONALITY VARCHAR2(25) CONSTRAINT NATIONALITY_NAME_NN NOT NULL
);

CREATE TABLE BINNACLE(
       ID_BINNACLE      NUMBER(5),
       ID_PERSON        NUMBER(5),
       DATE_CHANGE      DATE DEFAULT SYSDATE
);

CREATE TABLE KIND_PERSON(
       ID_KIND_PERSON   NUMBER(5),
       TITLE            VARCHAR2(25)
);

CREATE TABLE CATEGORY_X_PERSON(
       ID_PERSON        NUMBER(5),
       ID_CATEGORY      NUMBER(5)
);

CREATE TABLE CATEGORY_FAV(
       ID_CATEGORY_FAV  NUMBER(5),
       NAME_CATEGORY    VARCHAR2(25) CONSTRAINT CATEGORY_FAV_NAME_CATEGORY_NN NOT NULL
);

CREATE TABLE PROPOSAL_X_CATEGORY(
       ID_PROPOSAL      NUMBER(5),
       ID_CATEGORY_FAV  NUMBER(5)
);

CREATE TABLE PROPOSAL(
       ID_PROPOSAL      NUMBER(5),
       TITLE            VARCHAR2(25) CONSTRAINT PROPOSAL_TITLE_NN NOT NULL,
       DESCRIPTION_PROPOSAL          VARCHAR2(200) CONSTRAINT DESCRIPTION_PROPOSAL_NN NOT NULL,
       BUDGET           NUMBER(10),
       VOTE             NUMBER(5),
       DATE_PROPOSAL    DATE DEFAULT SYSDATE
);

CREATE TABLE VOTE(
       ID_PROPOSAL      NUMBER(5),
       ID_PERSON        NUMBER(5)
);

CREATE TABLE PERSON_X_PROPOSAL(
       ID_PROPOSAL      NUMBER(5),
       ID_PERSON        NUMBER(5)
);

CREATE TABLE PROPORSAL_X_COMMENT(
       ID_PROPORSAL     NUMBER(5),
       ID_COMMENT       NUMBER(5)
);

CREATE TABLE COMMENT_PROP(
       ID_COMMENT       NUMBER(5),
       DESCRIPTION_COMMENT   VARCHAR2(200) CONSTRAINT DESCRIPTION_COMMENT_NN NOT NULL,
       DATE_COMMENT     DATE DEFAULT SYSDATE
);

CREATE TABLE PERSON_X_COMMENT(
       ID_COMMENT       NUMBER(5),
       ID_PERSON        NUMBER(5)
);

CREATE TABLE PARAMETER(
       ID_PARAMETER     NUMBER(5),
       NAME_PARAMETER   VARCHAR2(20),
       VALUE_PARAMETER  VARCHAR2(20)
