/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import Business.Funciones;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
/**
 *
 * @author Kenneth
 */
public class adminDataModify extends javax.swing.JFrame {

    /**
     * Creates new form adminDataModify
     */
<<<<<<< HEAD
    public adminDataModify(int pUserType,String pCedula) {
=======
    public adminDataModify(int pUserType,String pCedula,int pComunidad) {
>>>>>>> Steven
        initComponents();
        setVisibleAll();
        this.userType=pUserType;
        this.cedula=pCedula;
        this.comunidad=pComunidad;
        
    }

    public static int userType;
    public static String cedula;
    public static int comunidad;
    
    private void llenarComboProvincias(String pCountry) throws SQLException{
        Funciones business = new Funciones();
        ResultSet provinces=business.getProvinces(pCountry);
        //nationalities.beforeFirst();
        while(provinces.next()){
            comboProvincia.addItem(provinces.getString("PROVINCE_NAME"));
        }
    } 
    private void llenarComboProvincias1(String pCountry) throws SQLException{
        Funciones business = new Funciones();
        ResultSet provinces=business.getProvinces(pCountry);
        //nationalities.beforeFirst();
        while(provinces.next()){
            comboProvincia1.addItem(provinces.getString("PROVINCE_NAME"));
        }
    } 
    
    private void llenarComboPaises() throws SQLException{
        Funciones business = new Funciones();
        ResultSet countries=business.getPaises();
        //nationalities.beforeFirst();
        while(countries.next()){
            comboPais.addItem(countries.getString("COUNTRY_NAME"));
        }
    }  
    private void llenarComboPaises1() throws SQLException{
        Funciones business = new Funciones();
        ResultSet countries=business.getPaises();
        //nationalities.beforeFirst();
        while(countries.next()){
            comboPais1.addItem(countries.getString("COUNTRY_NAME"));
        }
    } 
    private void llenarComboNacionalidades() throws SQLException{
        Funciones business = new Funciones();
        ResultSet nationalities=business.getNationalities(-1);
        //nationalities.beforeFirst();
        while(nationalities.next()){
            comboNacionalidad1.addItem(nationalities.getString("NATIONALITY_NAME"));
        }
    }
    private void llenarComboComunidades1(String pCanton) throws SQLException{
        Funciones business = new Funciones();
        ResultSet nationalities=business.getComunidades(pCanton);
        //nationalities.beforeFirst();
        while(nationalities.next()){
            comboComunidad1.addItem(nationalities.getString("COMMUNITY_NAME"));
        }
    }
    private void llenarComboCategorias() throws SQLException{
        Funciones business = new Funciones();
        ResultSet categories=business.getCategories(-1);
        //nationalities.beforeFirst();
        while(categories.next()){
            comboCategoria1.addItem(categories.getString("CATEGORY_NAME"));
        }
    }
    private void llenarComboCantones(String pProvince) throws SQLException{
        Funciones business = new Funciones();
        ResultSet cantones=business.getCantons(pProvince);
        //nationalities.beforeFirst();
        while(cantones.next()){
            comboCanton.addItem(cantones.getString("CANTON_NAME"));
        }
    } 
    private void llenarComboCantones1(String pProvince) throws SQLException{
        Funciones business = new Funciones();
        ResultSet cantones=business.getCantons(pProvince);
        //nationalities.beforeFirst();
        while(cantones.next()){
            comboCanton1.addItem(cantones.getString("CANTON_NAME"));
        }
    }/**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        kButton1 = new keeptoo.KButton();
        kButton2 = new keeptoo.KButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        lblProvincia = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        comboProvincia = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        comboEdicion2 = new javax.swing.JComboBox<>();
        lblCanton = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        comboCanton = new javax.swing.JComboBox<>();
        jTextField3 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        comboEdicion3 = new javax.swing.JComboBox<>();
        lblpais1 = new javax.swing.JLabel();
        comboPais1 = new javax.swing.JComboBox<>();
        lblProvincia1 = new javax.swing.JLabel();
        comboProvincia1 = new javax.swing.JComboBox<>();
        lblCanton1 = new javax.swing.JLabel();
        comboCanton1 = new javax.swing.JComboBox<>();
        lblComunidad1 = new javax.swing.JLabel();
        comboComunidad1 = new javax.swing.JComboBox<>();
        comboNacionalidad1 = new javax.swing.JComboBox<>();
        lblNacionalidad1 = new javax.swing.JLabel();
        lblCategoria1 = new javax.swing.JLabel();
        comboCategoria1 = new javax.swing.JComboBox<>();
        lblPais = new javax.swing.JLabel();
        comboPais = new javax.swing.JComboBox<>();
        kGradientPanel2 = new keeptoo.KGradientPanel();
        btnMainMenu = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kButton1.setText("Añadir");
        kButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton1ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(kButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 230, -1, -1));

        kButton2.setText("Modificar");
        kButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton2ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(kButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 470, -1, -1));
        kGradientPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 590, 980, 10));
        kGradientPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 980, 20));

        lblProvincia.setText("Seleccione Provincia a la que pertenecerá el cantón:");
        kGradientPanel1.add(lblProvincia, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 150, -1, 50));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 160, 190, 40));

        jLabel3.setText("Ingrese el nuevo Dato");
        kGradientPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 110, 130, 40));

        comboProvincia.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        comboProvincia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        comboProvincia.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, new java.awt.Color(0, 0, 0)));
        comboProvincia.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        comboProvincia.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboProvinciaItemStateChanged(evt);
            }
        });
        comboProvincia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboProvinciaActionPerformed(evt);
            }
        });
        kGradientPanel1.add(comboProvincia, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 200, 220, 30));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cancel36px.png"))); // NOI18N
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        kGradientPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 10, -1, -1));

        jLabel4.setText("Seleccione la tabla donde desea  agregar datos");
        kGradientPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 240, 50));

        comboEdicion2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        comboEdicion2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nacionalidad", "Categoría de propuesta", "País", "Provincia", "Cantón", "Comunidad", " ", " " }));
        comboEdicion2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, new java.awt.Color(0, 0, 0)));
        comboEdicion2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        comboEdicion2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboEdicion2ItemStateChanged(evt);
            }
        });
        comboEdicion2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboEdicion2ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(comboEdicion2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 220, 30));

        lblCanton.setText("Seleccione Cantón al que pertenecerá la comunidad:");
        kGradientPanel1.add(lblCanton, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 230, -1, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("Modificar  Catalogos");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        kGradientPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, -1, 50));

        comboCanton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        comboCanton.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        comboCanton.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, new java.awt.Color(0, 0, 0)));
        comboCanton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        comboCanton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboCantonActionPerformed(evt);
            }
        });
        kGradientPanel1.add(comboCanton, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 270, 220, 30));

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 400, 190, 40));

        jLabel13.setText("Ingrese el nuevo Dato");
        kGradientPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 350, 130, 40));

        jLabel14.setText("Seleccione la tabla donde desea  modificar datos");
        kGradientPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 240, 50));

        comboEdicion3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        comboEdicion3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nacionalidad", "Categoría de propuesta", "País", "Provincia", "Cantón", "Comunidad", " ", " " }));
        comboEdicion3.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, new java.awt.Color(0, 0, 0)));
        comboEdicion3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        comboEdicion3.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboEdicion3ItemStateChanged(evt);
            }
        });
        comboEdicion3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboEdicion3ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(comboEdicion3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 220, 30));

        lblpais1.setText("Seleccione el Pais:");
        kGradientPanel1.add(lblpais1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 320, 160, 50));

        comboPais1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        comboPais1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        comboPais1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, new java.awt.Color(0, 0, 0)));
        comboPais1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        comboPais1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboPais1ItemStateChanged(evt);
            }
        });
        comboPais1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboPais1ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(comboPais1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 360, 220, 30));

        lblProvincia1.setText("Seleccione la provincia:");
        kGradientPanel1.add(lblProvincia1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 390, -1, 30));

        comboProvincia1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        comboProvincia1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        comboProvincia1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, new java.awt.Color(0, 0, 0)));
        comboProvincia1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        comboProvincia1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboProvincia1ItemStateChanged(evt);
            }
        });
        comboProvincia1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboProvincia1ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(comboProvincia1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 420, 220, -1));

        lblCanton1.setText("Seleccione el canton:");
        kGradientPanel1.add(lblCanton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 440, 160, 50));

        comboCanton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        comboCanton1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        comboCanton1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, new java.awt.Color(0, 0, 0)));
        comboCanton1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        comboCanton1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboCanton1ItemStateChanged(evt);
            }
        });
        comboCanton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboCanton1ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(comboCanton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 480, 220, -1));

        lblComunidad1.setText("Seleccione la comunidad:");
        kGradientPanel1.add(lblComunidad1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 510, -1, 30));

        comboComunidad1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        comboComunidad1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        comboComunidad1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, new java.awt.Color(0, 0, 0)));
        comboComunidad1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        comboComunidad1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboComunidad1ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(comboComunidad1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 540, 220, 30));

        comboNacionalidad1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        comboNacionalidad1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        comboNacionalidad1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, new java.awt.Color(0, 0, 0)));
        comboNacionalidad1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        comboNacionalidad1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboNacionalidad1ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(comboNacionalidad1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, 220, 30));

        lblNacionalidad1.setText("Seleccione la nacionalidad:");
        kGradientPanel1.add(lblNacionalidad1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 160, 50));

        lblCategoria1.setText("Seleccione la categoría:");
        kGradientPanel1.add(lblCategoria1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, 160, 50));

        comboCategoria1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        comboCategoria1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        comboCategoria1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, new java.awt.Color(0, 0, 0)));
        comboCategoria1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        comboCategoria1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboCategoria1ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(comboCategoria1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 540, 220, 30));

        lblPais.setText("SeleccionePais al que pertenecerá la provincia:");
        kGradientPanel1.add(lblPais, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, -1, 50));

        comboPais.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        comboPais.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        comboPais.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, new java.awt.Color(0, 0, 0)));
        comboPais.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        comboPais.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboPaisItemStateChanged(evt);
            }
        });
        comboPais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboPaisActionPerformed(evt);
            }
        });
        kGradientPanel1.add(comboPais, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 130, 220, 30));

        getContentPane().add(kGradientPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, 800, 580));

        kGradientPanel2.setkEndColor(new java.awt.Color(51, 0, 204));
        kGradientPanel2.setkStartColor(new java.awt.Color(204, 0, 204));
        kGradientPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnMainMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/home.png"))); // NOI18N
        btnMainMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMainMenuMouseClicked(evt);
            }
        });
        kGradientPanel2.add(btnMainMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 60, 60));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Menú Principal");
        kGradientPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 110, 40));

        getContentPane().add(kGradientPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void comboProvinciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboProvinciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboProvinciaActionPerformed

    private void kButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton1ActionPerformed
    if(jTextField1.getText()!=null){
        try {
            Funciones business=new Funciones();
            if(comboEdicion2.getSelectedIndex()==0) business.insertNationality(jTextField1.getText());
            else if (comboEdicion2.getSelectedIndex()==1)  business.insertCategory(jTextField1.getText());
            else if (comboEdicion2.getSelectedIndex()==2)  business.insertCountry(jTextField1.getText());
            else if (comboEdicion2.getSelectedIndex()==3) business.insertProvince(jTextField1.getText(),1);
            else if (comboEdicion2.getSelectedIndex()==4)  {
                int province=business.getProvinceId((String)comboProvincia.getSelectedItem());
                business.insertCanton(jTextField1.getText(),province);
            }
            else if (comboEdicion2.getSelectedIndex()==5) {
                int province=business.getProvinceId((String)comboProvincia.getSelectedItem());
                int canton=business.getCantonId((String)comboCanton.getSelectedItem());
                business.insertCommunity(jTextField1.getText(),canton);
            }
                        
            JOptionPane.showMessageDialog(null,"Se ha agregado el dato correctamente al catálogo de: "+(String)comboEdicion2.getSelectedItem());
            
        } catch (SQLException ex) {
<<<<<<< HEAD
            Logger.getLogger(adminDataModify.class.getName()).log(Level.SEVERE, null, ex);
=======
            JOptionPane.showMessageDialog(null,"Por favor ingrese un nuevo dato para agregar al catálogo"+(String)comboEdicion2.getSelectedItem());            Logger.getLogger(adminDataModify.class.getName()).log(Level.SEVERE, null, ex);
>>>>>>> Steven
        }
    } else  JOptionPane.showMessageDialog(null,"Por favor ingrese un nuevo dato para agregar al catálogo"+(String)comboEdicion2.getSelectedItem());


    }//GEN-LAST:event_kButton1ActionPerformed

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel8MouseClicked

    private void btnMainMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMainMenuMouseClicked
        try {
<<<<<<< HEAD
            mainWindow ventana =new mainWindow(userType,cedula);
=======
            mainWindow ventana =new mainWindow(userType,cedula,comunidad);
>>>>>>> Steven
            ventana.setVisible(true);
            this.dispose();
        } catch (SQLException ex) {
            Logger.getLogger(adminDataModify.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnMainMenuMouseClicked

    private void comboEdicion2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboEdicion2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboEdicion2ActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked

    }//GEN-LAST:event_jLabel1MouseClicked

    private void comboCantonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboCantonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboCantonActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void kButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton2ActionPerformed
     if(jTextField3.getText()!=null){
        try {
            Funciones business=new Funciones();
            if(comboEdicion2.getSelectedIndex()==0) business.setNationality((String)comboNacionalidad1.getSelectedItem(),jTextField3.getText());
            else if (comboEdicion2.getSelectedIndex()==1)  business.setCategory((String)comboNacionalidad1.getSelectedItem(),jTextField3.getText());
            else if (comboEdicion2.getSelectedIndex()==2)  business.setCountry((String)comboPais1.getSelectedItem(),jTextField3.getText());
            else if (comboEdicion2.getSelectedIndex()==3) business.setProvince((String)comboProvincia1.getSelectedItem(),jTextField3.getText());
            else if (comboEdicion2.getSelectedIndex()==4)  business.setCanton((String)comboCanton1.getSelectedItem(),jTextField3.getText());
            else if (comboEdicion2.getSelectedIndex()==5) business.setCommunity((String)comboComunidad1.getSelectedItem(),jTextField3.getText());
                        
            JOptionPane.showMessageDialog(null,"Se ha agregado el dato correctamente al catálogo de: "+(String)comboEdicion3.getSelectedItem());
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,"Por favor ingrese un nuevo dato para agregar al catálogo"+(String)comboEdicion3.getSelectedItem());            Logger.getLogger(adminDataModify.class.getName()).log(Level.SEVERE, null, ex);
        }
    } else  JOptionPane.showMessageDialog(null,"Por favor ingrese un nuevo dato para agregar al catálogo"+(String)comboEdicion3.getSelectedItem());



    }//GEN-LAST:event_kButton2ActionPerformed

    private void comboEdicion3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboEdicion3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboEdicion3ActionPerformed

    private void comboPais1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboPais1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboPais1ActionPerformed

    private void comboProvincia1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboProvincia1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboProvincia1ActionPerformed

    private void comboCanton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboCanton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboCanton1ActionPerformed

    private void comboComunidad1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboComunidad1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboComunidad1ActionPerformed

    private void comboEdicion2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboEdicion2ItemStateChanged
        setVisibleAll();
        clearCombos1();
            if(comboEdicion2.getSelectedIndex()==3) {
            try {
                lblPais.setVisible(true);
                comboPais.setVisible(true);
                llenarComboPaises();
            } catch (SQLException ex) {
                Logger.getLogger(adminDataModify.class.getName()).log(Level.SEVERE, null, ex);
            }

            }
            if(comboEdicion2.getSelectedIndex()==4) {
            try {
                llenarComboPaises();
            } catch (SQLException ex) {
                Logger.getLogger(adminDataModify.class.getName()).log(Level.SEVERE, null, ex);
            }
                lblProvincia.setVisible(true);
                comboProvincia.setVisible(true);
                lblPais.setVisible(true);
                comboPais.setVisible(true);
            }
            if(comboEdicion2.getSelectedIndex()==5){
            try{
                llenarComboPaises();
                lblPais.setVisible(true);
                comboPais.setVisible(true);
                lblProvincia.setVisible(true);
                comboProvincia.setVisible(true);
                lblCanton.setVisible(true);
                comboCanton.setVisible(true);
            } catch (SQLException ex) {
                Logger.getLogger(adminDataModify.class.getName()).log(Level.SEVERE, null, ex);
            }
            }
    }//GEN-LAST:event_comboEdicion2ItemStateChanged

    private void comboProvinciaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboProvinciaItemStateChanged
        comboCanton.removeAllItems();
        try {
            llenarComboCantones((String)comboProvincia.getSelectedItem());
        } catch (SQLException ex) {
            Logger.getLogger(adminDataModify.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_comboProvinciaItemStateChanged
private void clearCombos(){
    comboProvincia1.removeAllItems();
    comboCanton1.removeAllItems();
    comboNacionalidad1.removeAllItems();
    comboPais1.removeAllItems();
    comboProvincia1.removeAllItems();
    comboCanton1.removeAllItems();
    comboComunidad1.removeAllItems();
    
    lblProvincia1.setVisible(false);
    comboProvincia1.setVisible(false);
    lblCanton1.setVisible(false);
    comboCanton1.setVisible(false);
    lblpais1.setVisible(false);
    comboPais1.setVisible(false);   
    lblComunidad1.setVisible(false);
    comboComunidad1.setVisible(false);  
        comboCategoria1.removeAllItems();
    comboNacionalidad1.removeAllItems();
      lblNacionalidad1.setVisible(false);
    comboNacionalidad1.setVisible(false);
    lblCategoria1.setVisible(false);
    comboCategoria1.setVisible(false);
}
private void clearCombos1(){
    comboProvincia.removeAllItems();
    comboCanton.removeAllItems();
    comboPais.removeAllItems();
    comboProvincia.removeAllItems();
    comboCanton.removeAllItems();

    
    lblProvincia.setVisible(false);
    comboProvincia.setVisible(false);
    lblCanton.setVisible(false);
    comboCanton.setVisible(false);
    lblPais.setVisible(false);
    comboPais.setVisible(false);  

}
public void setVisibleAll(){
    lblPais.setVisible(false);
    lblCanton.setVisible(false);
    lblProvincia.setVisible(false);
    
    lblpais1.setVisible(false);
    lblCanton1.setVisible(false);
    lblComunidad1.setVisible(false);
    lblNacionalidad1.setVisible(false);
    lblCategoria1.setVisible(false);
    lblProvincia1.setVisible(false);
    
    comboPais.setVisible(false);
    comboProvincia.setVisible(false);
    comboCanton.setVisible(false);
    
    comboPais1.setVisible(false);
    comboCanton1.setVisible(false);
    comboProvincia1.setVisible(false);
    comboComunidad1.setVisible(false);
    comboCategoria1.setVisible(false);
    comboNacionalidad1.setVisible(false);
}
    private void comboEdicion3ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboEdicion3ItemStateChanged
            setVisibleAll();
            clearCombos();
            if(comboEdicion3.getSelectedIndex()==0) {
                try {
                    lblNacionalidad1.setVisible(true);
                    comboNacionalidad1.setVisible(true);
                    llenarComboNacionalidades();
                } catch (SQLException ex) {
                    Logger.getLogger(adminDataModify.class.getName()).log(Level.SEVERE, null, ex);
                }
                
            }
            if(comboEdicion3.getSelectedIndex()==1) {
                lblCategoria1.setVisible(true);
                comboCategoria1.setVisible(true);
                try {
                    llenarComboCategorias();
                } catch (SQLException ex) {
                    Logger.getLogger(adminDataModify.class.getName()).log(Level.SEVERE, null, ex);
                }
                
            }
            if(comboEdicion3.getSelectedIndex()==2) {
                lblpais1.setVisible(true);
                comboPais1.setVisible(true);
                try {
                    llenarComboPaises1();
                } catch (SQLException ex) {
                    Logger.getLogger(adminDataModify.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            if(comboEdicion3.getSelectedIndex()==3) {
                try {
                    llenarComboPaises1();
                } catch (SQLException ex) {
                    Logger.getLogger(adminDataModify.class.getName()).log(Level.SEVERE, null, ex);
                }
                lblpais1.setVisible(true);
                comboPais1.setVisible(true);
                lblProvincia1.setVisible(true);
                comboProvincia1.setVisible(true);
            }
            if(comboEdicion3.getSelectedIndex()==4){
                try {
                    llenarComboPaises1();
                } catch (SQLException ex) {
                    Logger.getLogger(adminDataModify.class.getName()).log(Level.SEVERE, null, ex);
                }
                lblpais1.setVisible(true);
                comboPais1.setVisible(true);
                lblProvincia1.setVisible(true);
                comboProvincia1.setVisible(true);
                lblCanton1.setVisible(true);
                comboCanton1.setVisible(true);         
            }
            if(comboEdicion3.getSelectedIndex()==5){
                try {
                    llenarComboPaises1();
                } catch (SQLException ex) {
                    Logger.getLogger(adminDataModify.class.getName()).log(Level.SEVERE, null, ex);
                }
                lblpais1.setVisible(true);
                comboPais1.setVisible(true);
                lblProvincia1.setVisible(true);
                comboProvincia1.setVisible(true);
                lblCanton1.setVisible(true);
                comboCanton1.setVisible(true);
                lblComunidad1.setVisible(true);
                comboComunidad1.setVisible(true); 
            }
    }//GEN-LAST:event_comboEdicion3ItemStateChanged

    private void comboNacionalidad1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboNacionalidad1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboNacionalidad1ActionPerformed

    private void comboCategoria1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboCategoria1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboCategoria1ActionPerformed

    private void comboPais1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboPais1ItemStateChanged
        comboProvincia1.removeAllItems();
        try {
            llenarComboProvincias1((String)comboPais1.getSelectedItem());
        } catch (SQLException ex) {
            Logger.getLogger(adminDataModify.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_comboPais1ItemStateChanged

    private void comboProvincia1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboProvincia1ItemStateChanged
        comboCanton1.removeAllItems();
        try {
            llenarComboCantones1((String)comboProvincia1.getSelectedItem());
        } catch (SQLException ex) {
            Logger.getLogger(adminDataModify.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_comboProvincia1ItemStateChanged

    private void comboCanton1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboCanton1ItemStateChanged
        comboComunidad1.removeAllItems();
        try {
            llenarComboComunidades1((String)comboCanton1.getSelectedItem());
        } catch (SQLException ex) {
            Logger.getLogger(adminDataModify.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_comboCanton1ItemStateChanged

    private void comboPaisItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboPaisItemStateChanged
    comboProvincia.removeAllItems();
    comboCanton.removeAllItems();
        try {
            llenarComboProvincias((String)comboPais.getSelectedItem());
        } catch (SQLException ex) {
            Logger.getLogger(adminDataModify.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_comboPaisItemStateChanged

    private void comboPaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboPaisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboPaisActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adminDataModify.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adminDataModify.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminDataModify.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminDataModify.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
*/
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
<<<<<<< HEAD
                new adminDataModify(userType,cedula).setVisible(true);
=======
                new adminDataModify(userType,cedula,comunidad).setVisible(true);
>>>>>>> Steven
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnMainMenu;
    private javax.swing.JComboBox<String> comboCanton;
    private javax.swing.JComboBox<String> comboCanton1;
    private javax.swing.JComboBox<String> comboCategoria1;
    private javax.swing.JComboBox<String> comboComunidad1;
    private javax.swing.JComboBox<String> comboEdicion2;
    private javax.swing.JComboBox<String> comboEdicion3;
    private javax.swing.JComboBox<String> comboNacionalidad1;
    private javax.swing.JComboBox<String> comboPais;
    private javax.swing.JComboBox<String> comboPais1;
    private javax.swing.JComboBox<String> comboProvincia;
    private javax.swing.JComboBox<String> comboProvincia1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField3;
    private keeptoo.KButton kButton1;
    private keeptoo.KButton kButton2;
    private keeptoo.KGradientPanel kGradientPanel1;
    private keeptoo.KGradientPanel kGradientPanel2;
    private javax.swing.JLabel lblCanton;
    private javax.swing.JLabel lblCanton1;
    private javax.swing.JLabel lblCategoria1;
    private javax.swing.JLabel lblComunidad1;
    private javax.swing.JLabel lblNacionalidad1;
    private javax.swing.JLabel lblPais;
    private javax.swing.JLabel lblProvincia;
    private javax.swing.JLabel lblProvincia1;
    private javax.swing.JLabel lblpais1;
    // End of variables declaration//GEN-END:variables
}
