/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import java.awt.Color;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTextField;
import javax.swing.SpinnerNumberModel;

/**
 *
 * @author kenneth
 */
public class mainWindow extends javax.swing.JFrame {

    /**
     * Creates new form mainWindow
     */
    public mainWindow() {
        initComponents();
        try {
            //this.mainPanel.setBackground(new Color(0,0,0,80));
            //this.panelScroll.setBackground(new Color(0,0,0,80));
            connect.connectDB.getProposal(-1, -1, null,null,-1);
        } catch (SQLException ex) {
            System.out.println("Me cago");
        }
        for(int i=30;i<1000;i+=170){
            crearPaneles(i);
        }
        
    }
    
    
 private void cargarPropuestas(){
     
 }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel2 = new keeptoo.KGradientPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        mainPanel = new javax.swing.JScrollPane();
        panelScroll = new javax.swing.JPanel();
        checkBox = new javax.swing.JCheckBox();
        cbxCombo = new javax.swing.JComboBox<>();
        kButton1 = new keeptoo.KButton();
        panelFiltros = new javax.swing.JPanel();
        panelMenu = new keeptoo.KGradientPanel();
        btnHome = new javax.swing.JLabel();
        btnNewProposal = new javax.swing.JLabel();
        btnConfig = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kGradientPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cancel36px.png"))); // NOI18N
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        kGradientPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 20, -1, 40));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("Propuestas");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        kGradientPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 60, -1, 50));

        mainPanel.setBackground(new Color(0,0,0,80));
        mainPanel.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        panelScroll.setBackground(new Color(0,0,0,80));
        panelScroll.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        mainPanel.setViewportView(panelScroll);

        kGradientPanel2.add(mainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 760, 290));

        checkBox.setText("Aplicar Filtro");
        checkBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxActionPerformed(evt);
            }
        });
        kGradientPanel2.add(checkBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 160, -1, -1));

        cbxCombo.setBackground(new java.awt.Color(204, 0, 204));
        cbxCombo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbxCombo.setMaximumRowCount(5);
        cbxCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Selecciona una Opcion-", "Fecha", "Clasificacion", "Mis Propuestas", "Top Propuestas" }));
        cbxCombo.setToolTipText("");
        cbxCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxComboActionPerformed(evt);
            }
        });
        kGradientPanel2.add(cbxCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 190, -1));

        kButton1.setText("Consultar");
        kGradientPanel2.add(kButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 190, 70, 30));

        panelFiltros.setBackground(new Color(0,0,0,80));
        panelFiltros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelFiltrosMouseClicked(evt);
            }
        });
        panelFiltros.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        kGradientPanel2.add(panelFiltros, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 760, 100));

        getContentPane().add(kGradientPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 790, 560));

        panelMenu.setkEndColor(new java.awt.Color(51, 0, 204));
        panelMenu.setkStartColor(new java.awt.Color(204, 0, 204));
        panelMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/home.png"))); // NOI18N
        btnHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHomeMouseClicked(evt);
            }
        });
        panelMenu.add(btnHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, -1, -1));

        btnNewProposal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/newProposal.png"))); // NOI18N
        btnNewProposal.setText("jLabel8");
        btnNewProposal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNewProposalMouseClicked(evt);
            }
        });
        panelMenu.add(btnNewProposal, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, 60, -1));

        btnConfig.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/config.png"))); // NOI18N
        btnConfig.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnConfigMouseClicked(evt);
            }
        });
        panelMenu.add(btnConfig, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 450, -1, -1));

        getContentPane().add(panelMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel6MouseClicked
   //metodo que modifica el combobox con los filtros 
    private void cbxComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxComboActionPerformed
       panelFiltros.removeAll();//
       panelFiltros.repaint();
        String opcion=cbxCombo.getSelectedItem().toString();
       switch(opcion){
           case "Fecha":   
               filtros(1);
               break;
           case "Top Propuestas":
               filtros(2);
               break;
           case "Mis Propuestas":
               filtros(4);
               break;
           case "Clasificacion":
               filtros(3);
               break;
       } 
    }//GEN-LAST:event_cbxComboActionPerformed
    
    private void cargarMenu(){
        if(typeUser==1){
            
        }
    }
    
    
    
    private void btnHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseClicked
        // TODO add your handling code here:
        mainWindow ventana =new mainWindow();
        ventana.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_btnHomeMouseClicked

    private void btnNewProposalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNewProposalMouseClicked
        try {
            newProposal ventana =new newProposal();
            ventana.setVisible(true);
            this.dispose();
        } catch (SQLException ex) {
            Logger.getLogger(mainWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnNewProposalMouseClicked

    private void btnConfigMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConfigMouseClicked
        userConsultas ventana= new userConsultas();
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnConfigMouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        
    }//GEN-LAST:event_jLabel1MouseClicked

    private void panelFiltrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelFiltrosMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_panelFiltrosMouseClicked

    private void checkBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxActionPerformed
       String opcion=cbxCombo.getSelectedItem().toString();
       switch(opcion){
           case "Fecha":
               if(arreglo[0]==1)arreglo[0]=0;
               else{
                   arreglo[0]=1;
               }
               
               break;
           case "Top Propuestas":
               if(arreglo[3]==1)arreglo[3]=0;
               else{
                   arreglo[3]=1;
               }
               break;
           case "Mis Propuestas":
               if(arreglo[2]==1)arreglo[2]=0;
               else{
                   arreglo[2]=1;
               }
               break;
           case "Clasificacion":
               if(arreglo[1]==1)arreglo[1]=0;
               else{
                   arreglo[1]=1;
               }
               break;
       } 
       
       for (int i=0;i<arreglo.length;i++){
           System.out.print(arreglo[i]);
           
       }
       System.out.println("----");
    }//GEN-LAST:event_checkBoxActionPerformed
  
    
 
   private void panelMouseClicked(java.awt.event.MouseEvent evt,String letra){
       this.dispose();
       proposalVisualizer ventana = new proposalVisualizer();
       ventana.setVisible(true);
   } 
   

       
    public void filtros(int opc){
        switch (opc){
            case  1://opcion de fecha
             javax.swing.JLabel txtFecha1 =new javax.swing.JLabel();
             javax.swing.JLabel txtfecha2 =new javax.swing.JLabel();
             javax.swing.JLabel txtGuion=new javax.swing.JLabel();

            com.toedter.calendar.JDateChooser fechaDesde = new com.toedter.calendar.JDateChooser();
            com.toedter.calendar.JDateChooser fechaHasta = new com.toedter.calendar.JDateChooser();
            ((JTextField)fechaDesde.getDateEditor()).setEditable(false);
            ((JTextField)fechaHasta.getDateEditor()).setEditable(false);
                 
            panelFiltros.add(fechaDesde, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, 100, -1));
            txtFecha1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
            txtFecha1.setForeground(new java.awt.Color(255, 0, 204));
            txtFecha1.setText("Desde");
            
            panelFiltros.add(txtFecha1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 35, -1, -1));
            txtGuion.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
            txtGuion.setForeground(new java.awt.Color(255, 0, 204));
            txtGuion.setText("-");
            panelFiltros.add(txtGuion, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 35, -1, -1));
            panelFiltros.add(fechaHasta, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 40,100, -1));
            txtfecha2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
            txtfecha2.setForeground(new java.awt.Color(255, 0, 204));
            txtfecha2.setText("Hasta");
            panelFiltros.add(txtfecha2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 35, -1,-1));
            
           if(arreglo[0]==1){
               checkBox.setSelected(true);
           }
           else{
               checkBox.setSelected(false);  
           }
            
            
            pack();
            break;
            
            case 2://opcion top N
                spinnerTop= new javax.swing.JSpinner();
                javax.swing.JLabel txtTop= new javax.swing.JLabel();
                txtTop.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
                txtTop.setForeground(new java.awt.Color(255, 0, 204));
                txtTop.setText("TOP");
                panelFiltros.add(txtTop, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, -1, -1));
                spinnerTop.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
                spinnerTop.setModel(new SpinnerNumberModel(0, 0, 20, 1));
                panelFiltros.add(spinnerTop, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 40, 50, -1));
           if(arreglo[3]==1){
               checkBox.setSelected(true);
           }
           else{
               checkBox.setSelected(false);  
           }
               
                pack();
                break;
            case 3:// clasificacion
                comboCategoria = new javax.swing.JComboBox<String> ();
                javax.swing.JLabel txtCategoria= new javax.swing.JLabel();
                comboCategoria.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
                comboCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Psycho", "Gothic", "Amateur", "Bass" }));
                panelFiltros.add(comboCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 40, 100, -1));
                txtCategoria.setText("Categoria");
                txtCategoria.setForeground(new java.awt.Color(255, 0, 204));
                txtCategoria.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
                panelFiltros.add(txtCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, -1, -1));
                if(arreglo[1]==1){
               checkBox.setSelected(true);
           }
           else{
               checkBox.setSelected(false);  
           }
            
                pack();
                break;
            case 4://mis propuestas
               if(arreglo[2]==1){
               checkBox.setSelected(true);
           }
           else{
               checkBox.setSelected(false);  
           }
             
                pack();
                break;
                
                
                    
        }
        
    } 
    
    private void crearPaneles(int posY){
        javax.swing.JLabel txtMainTitle;
        javax.swing.JLabel txtTitulo;
        javax.swing.JPanel panelproposal;
        javax.swing.JTextField boxInfo;
        //creo el panel
        panelproposal = new javax.swing.JPanel();
        
        panelproposal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
       // panelproposal.setBackground(new Color(0,0,0,80));
        panelproposal.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(51, 51, 255)));
        //creo el titulo y lo inserto en el panel
        txtMainTitle = new javax.swing.JLabel();
        txtMainTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtMainTitle.setText("Titulo:");
        panelproposal.add(txtMainTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 5, -1, 50));
        //creo el subtitulo y lo inserto en el panel
        txtTitulo = new javax.swing.JLabel();
        txtTitulo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtTitulo.setText("aqui va el titulo de la propuesta");
        panelproposal.add(txtTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 210, 40));
        boxInfo = new javax.swing.JTextField();
        //creo e inserto la caja de texto
        boxInfo.setText("jTextField1");
        boxInfo.setBackground(new Color(0,0,0,100));
        boxInfo.setFont(new java.awt.Font("Segoe UI", 0, 14)); 
        panelproposal.add(boxInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 700, 90));
        
        this.panelScroll.add(panelproposal, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, posY, 860, 160));
        
        pack();
    }
    
    
    
  
 
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainWindow().setVisible(true);
            }
        });
    }
   
    //mi declaracion de variables 
   public static int typeUser;
    public javax.swing.JSpinner spinnerTop;
    public javax.swing.JComboBox<String> comboCategoria;
    public javax.swing.JButton btnAceptar;
    public int[ ] arreglo = {0, 0,0, 0}; 
    //fin de mi declaracion de variables
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnConfig;
    private javax.swing.JLabel btnHome;
    private javax.swing.JLabel btnNewProposal;
    private javax.swing.JComboBox<String> cbxCombo;
    private javax.swing.JCheckBox checkBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private keeptoo.KButton kButton1;
    private keeptoo.KGradientPanel kGradientPanel2;
    private javax.swing.JScrollPane mainPanel;
    private javax.swing.JPanel panelFiltros;
    private keeptoo.KGradientPanel panelMenu;
    private javax.swing.JPanel panelScroll;
    // End of variables declaration//GEN-END:variables
}
