/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

/**
 *
 * @author stevenpc
 */
public class PricipalMenu extends javax.swing.JFrame {

    /**
     * Creates new form PricipalMenu
     */
    public PricipalMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        btnHome = new javax.swing.JLabel();
        btnNewProposal = new javax.swing.JLabel();
        btnConfig = new javax.swing.JLabel();
        kGradientPanel2 = new keeptoo.KGradientPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnSignIn = new keeptoo.KButton();
        btnSignIn1 = new keeptoo.KButton();
        btnModuloEstadisticas = new keeptoo.KButton();
        btnSignIn3 = new keeptoo.KButton();
        btnModificarCatalogo = new keeptoo.KButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        kGradientPanel1.setkEndColor(new java.awt.Color(51, 0, 204));
        kGradientPanel1.setkStartColor(new java.awt.Color(204, 0, 204));
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/home.png"))); // NOI18N
        btnHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHomeMouseClicked(evt);
            }
        });
        kGradientPanel1.add(btnHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        btnNewProposal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/newProposal.png"))); // NOI18N
        btnNewProposal.setText("jLabel8");
        btnNewProposal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNewProposalMouseClicked(evt);
            }
        });
        kGradientPanel1.add(btnNewProposal, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 60, -1));

        btnConfig.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/config.png"))); // NOI18N
        btnConfig.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnConfigMouseClicked(evt);
            }
        });
        kGradientPanel1.add(btnConfig, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, -1, -1));

        kGradientPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cancel36px.png"))); // NOI18N
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        kGradientPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 10, -1, 40));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("Menú Principal");
        kGradientPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, -1, 50));

        btnSignIn.setText("Registrar Propuestas");
        btnSignIn.setBorderPainted(false);
        btnSignIn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSignInMouseClicked(evt);
            }
        });
        btnSignIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignInActionPerformed(evt);
            }
        });
        kGradientPanel2.add(btnSignIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 170, -1, -1));

        btnSignIn1.setText("Editar Perfil");
        btnSignIn1.setBorderPainted(false);
        btnSignIn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSignIn1MouseClicked(evt);
            }
        });
        btnSignIn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignIn1ActionPerformed(evt);
            }
        });
        kGradientPanel2.add(btnSignIn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, -1, -1));

        btnModuloEstadisticas.setText("Módulo de estadísticas");
        btnModuloEstadisticas.setBorderPainted(false);
        btnModuloEstadisticas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnModuloEstadisticasMouseClicked(evt);
            }
        });
        btnModuloEstadisticas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModuloEstadisticasActionPerformed(evt);
            }
        });
        kGradientPanel2.add(btnModuloEstadisticas, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 400, -1, -1));

        btnSignIn3.setText("Consultar Propuestas");
        btnSignIn3.setBorderPainted(false);
        btnSignIn3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSignIn3MouseClicked(evt);
            }
        });
        btnSignIn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignIn3ActionPerformed(evt);
            }
        });
        kGradientPanel2.add(btnSignIn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 300, -1, -1));

        btnModificarCatalogo.setText("Modificar Catálogos");
        btnModificarCatalogo.setBorderPainted(false);
        btnModificarCatalogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnModificarCatalogoMouseClicked(evt);
            }
        });
        btnModificarCatalogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarCatalogoActionPerformed(evt);
            }
        });
        kGradientPanel2.add(btnModificarCatalogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 300, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 176, Short.MAX_VALUE)
                .addComponent(kGradientPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 753, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(kGradientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 752, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 505, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 505, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseClicked
        // TODO add your handling code here:
        mainWindow ventana =new mainWindow();
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnHomeMouseClicked

    private void btnNewProposalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNewProposalMouseClicked

    }//GEN-LAST:event_btnNewProposalMouseClicked

    private void btnConfigMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConfigMouseClicked

    }//GEN-LAST:event_btnConfigMouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel6MouseClicked

    private void btnSignInMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSignInMouseClicked

    }//GEN-LAST:event_btnSignInMouseClicked

    private void btnSignInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignInActionPerformed

    }//GEN-LAST:event_btnSignInActionPerformed

    private void btnSignIn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSignIn1MouseClicked

    }//GEN-LAST:event_btnSignIn1MouseClicked

    private void btnSignIn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignIn1ActionPerformed
        userConsultas ventana =new userConsultas();
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSignIn1ActionPerformed

    private void btnModuloEstadisticasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModuloEstadisticasMouseClicked

    }//GEN-LAST:event_btnModuloEstadisticasMouseClicked

    private void btnModuloEstadisticasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModuloEstadisticasActionPerformed

    }//GEN-LAST:event_btnModuloEstadisticasActionPerformed

    private void btnSignIn3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSignIn3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSignIn3MouseClicked

    private void btnSignIn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignIn3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSignIn3ActionPerformed

    private void btnModificarCatalogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModificarCatalogoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnModificarCatalogoMouseClicked

    private void btnModificarCatalogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarCatalogoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnModificarCatalogoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PricipalMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PricipalMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PricipalMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PricipalMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PricipalMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnConfig;
    private javax.swing.JLabel btnHome;
    private keeptoo.KButton btnModificarCatalogo;
    private keeptoo.KButton btnModuloEstadisticas;
    private javax.swing.JLabel btnNewProposal;
    private keeptoo.KButton btnSignIn;
    private keeptoo.KButton btnSignIn1;
    private keeptoo.KButton btnSignIn3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private keeptoo.KGradientPanel kGradientPanel1;
    private keeptoo.KGradientPanel kGradientPanel2;
    // End of variables declaration//GEN-END:variables
}
