/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import Business.Funciones;
import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;

/**
 *
 * @author Kenneth
 */
public class SignUpLocation extends javax.swing.JFrame {

    /**
     * Creates new form SignUpLocation
     */
    public SignUpLocation() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        comboPais = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        comboProvincia = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        comboCanton = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        comboComunidad = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        btnSignIn = new keeptoo.KButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kGradientPanel1.setBackground(new java.awt.Color(255, 255, 255));
        kGradientPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        kGradientPanel1.setkEndColor(new java.awt.Color(255, 0, 204));
        kGradientPanel1.setkStartColor(new java.awt.Color(51, 51, 255));
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Por favor seleccione la comunidad a la que pertenece");
        kGradientPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 540, 80));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cancel36px.png"))); // NOI18N
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        kGradientPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 20, -1, -1));

        comboPais.setBackground(new java.awt.Color(204, 255, 204));
        comboPais.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        comboPais.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, new java.awt.Color(0, 0, 0)));
        comboPais.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        comboPais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboPaisActionPerformed(evt);
            }
        });
        kGradientPanel1.add(comboPais, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 250, 40));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 0, 204));
        jLabel8.setText("1) Pais");
        kGradientPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 250, 20));

        comboProvincia.setBackground(new java.awt.Color(204, 255, 204));
        comboProvincia.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        comboProvincia.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, new java.awt.Color(0, 0, 0)));
        comboProvincia.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        comboProvincia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboProvinciaActionPerformed(evt);
            }
        });
        kGradientPanel1.add(comboProvincia, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 320, 250, 40));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 0, 204));
        jLabel9.setText("2) Provincia");
        kGradientPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, 250, 20));

        comboCanton.setBackground(new java.awt.Color(204, 255, 204));
        comboCanton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        comboCanton.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, new java.awt.Color(0, 0, 0)));
        comboCanton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        comboCanton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboCantonActionPerformed(evt);
            }
        });
        kGradientPanel1.add(comboCanton, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 410, 250, 40));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 0, 204));
        jLabel10.setText("3) Cantón");
        kGradientPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 380, 250, 20));

        comboComunidad.setBackground(new java.awt.Color(204, 255, 204));
        comboComunidad.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        comboComunidad.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, new java.awt.Color(0, 0, 0)));
        comboComunidad.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        comboComunidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboComunidadActionPerformed(evt);
            }
        });
        kGradientPanel1.add(comboComunidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 490, 250, 40));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 0, 204));
        jLabel11.setText("4) Comunidad");
        kGradientPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 460, 250, 20));

        btnSignIn.setText("ENTRAR");
        btnSignIn.setActionCommand("Ingresar");
        btnSignIn.setBorderPainted(false);
        btnSignIn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSignInMouseClicked(evt);
            }
        });
        btnSignIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignInActionPerformed(evt);
            }
        });
        kGradientPanel1.add(btnSignIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 340, -1, -1));

        getContentPane().add(kGradientPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 800, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel7MouseClicked

    private void comboPaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboPaisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboPaisActionPerformed

    private void comboProvinciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboProvinciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboProvinciaActionPerformed

    private void comboCantonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboCantonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboCantonActionPerformed

    private void comboComunidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboComunidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboComunidadActionPerformed

    private void btnSignInMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSignInMouseClicked
        try {
            Funciones utilidades = new Funciones();
 //           String user = this.txtUser.getText();
            //char[] passw = this.txtPassw.getPassword();
            //String passwF = new String(passw);
//            String passwF=this.txtPassw.getText();

  //          int validation=utilidades.correctLogIn(user, passwF);
            if(validation!=-1){
                mainWindow ventana;
                JOptionPane.showMessageDialog(null, "Ha ingresado un usuario de tipo "+validation);

                ventana = new mainWindow();
                ventana.setVisible(true);
                this.dispose();
            }
            else{
                JOptionPane.showMessageDialog(null, "Constraseña o Usuario incorrecto");
            }
        } catch (SQLException ex) {
            Logger.getLogger(SingIn.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSignInMouseClicked

    private void btnSignInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignInActionPerformed

    }//GEN-LAST:event_btnSignInActionPerformed
    private void llenarComboPaises() throws SQLException{
        Funciones business = new Funciones();
        ResultSet countries=business.getCountries(-1);
        //nationalities.beforeFirst();
        while(countries.next()){
            comboPais.addItem(countries.getString("COUNTRY_NAME"));
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUpLocation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUpLocation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUpLocation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUpLocation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUpLocation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private keeptoo.KButton btnSignIn;
    private javax.swing.JComboBox<String> comboCanton;
    private javax.swing.JComboBox<String> comboComunidad;
    private javax.swing.JComboBox<String> comboPais;
    private javax.swing.JComboBox<String> comboProvincia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private keeptoo.KGradientPanel kGradientPanel1;
    // End of variables declaration//GEN-END:variables
}
