------------ CREACION DE SEQUENCIA PARA EL ID DE NACIONALIDAD-----
CREATE SEQUENCE s_nationality   
  START WITH 0
  INCREMENT BY 1
  MINVALUE 0
  MAXVALUE 10000000
  NOCACHE
  NOCYCLE;
------------ CREACION DE SEQUENCIA PARA EL ID DE PAIS-----
CREATE SEQUENCE s_country   
  START WITH 1
  INCREMENT BY 1
  MINVALUE 0
  MAXVALUE 10000000
  NOCACHE
  NOCYCLE;

------------ CREACION DE SEQUENCIA PARA EL ID DE PROVINCIA-----
CREATE SEQUENCE s_province  
  START WITH 1
  INCREMENT BY 1
  MINVALUE 0
  MAXVALUE 10000000
  NOCACHE
  NOCYCLE;
  
------------ CREACION DE SEQUENCIA PARA EL ID DE CATEGORIA-----
CREATE SEQUENCE s_category   
  START WITH 0
  INCREMENT BY 1
  MINVALUE 0
  MAXVALUE 10000000
  NOCACHE
  NOCYCLE;
  
------------ CREACION DE SEQUENCIA PARA EL ID DE CANTON-----
CREATE SEQUENCE s_canton
  START WITH 1
  INCREMENT BY 1
  MINVALUE 0
  MAXVALUE 10000000
  NOCACHE
  NOCYCLE;  
  
------------ CREACION DE SEQUENCIA PARA EL ID DE COMMUNITY-----
CREATE SEQUENCE s_community
  START WITH 1
  INCREMENT BY 1
  MINVALUE 0
  MAXVALUE 10000000
  NOCACHE
  NOCYCLE;
  
------------ CREACION DE SEQUENCIA PARA EL ID DE USERTYPE-----
CREATE SEQUENCE s_usertype  
  START WITH 0
  INCREMENT BY 1
  MINVALUE 0
  MAXVALUE 10000000
  NOCACHE
  NOCYCLE;
------------ CREACION DE SEQUENCIA PARA EL ID DE EMAIL DE LA PERSONA-----
CREATE SEQUENCE s_email
  START WITH 0
  INCREMENT BY 1
  MINVALUE 0
  MAXVALUE 10000000
  NOCACHE
  NOCYCLE;
  
------------ CREACION DE SEQUENCIA PARA EL ID DE TELEFONO DE LA PERSONA-----
CREATE SEQUENCE s_Telephone
  START WITH 0
  INCREMENT BY 1
  MINVALUE 0
  MAXVALUE 10000000
  NOCACHE
  NOCYCLE;
  
------------ CREACION DE SEQUENCIA PARA EL ID DE PROPUESTA-----
CREATE SEQUENCE s_proposal
  START WITH 0
  INCREMENT BY 1
  MINVALUE 0
  MAXVALUE 10000000
  NOCACHE
  NOCYCLE;
------------ CREACION DE SEQUENCIA PARA EL ID DE COMENTARIO-----
CREATE SEQUENCE s_comment
  START WITH 0
  INCREMENT BY 1
  MINVALUE 0
  MAXVALUE 10000000
  NOCACHE
  NOCYCLE;
  
------------ CREACION DE SEQUENCIA PARA EL ID DE PARAMETRO-----
CREATE SEQUENCE s_parameter
  START WITH 0
  INCREMENT BY 1
  MINVALUE 0
  MAXVALUE 10000000
  NOCACHE
  NOCYCLE;
  
------------ CREACION DE SEQUENCIA PARA EL ID DE VOTO-----
CREATE SEQUENCE s_vote
  START WITH 0
  INCREMENT BY 1
  MINVALUE 0
  MAXVALUE 10000000
  NOCACHE
  NOCYCLE;
  
------------ CREACION DE SEQUENCIA PARA EL ID DE BITÁCORA-----
CREATE SEQUENCE s_binnacle 
  START WITH 0
  INCREMENT BY 1
  MINVALUE 0
  MAXVALUE 10000000
  NOCACHE
  NOCYCLE;
