--ALTER TABLE COUNTRY RENAME COLUMN COUNTRY_NAME TO NAME_COUNTRY;

CREATE OR REPLACE PACKAGE PKG_ADMIN_COUNTRY  IS
       FUNCTION GET_ID_COUNTRY(PNCOUNTRY_NAME IN VARCHAR2)  RETURN NUMBER;
       FUNCTION GET_NAME_COUNTRY(PNID_COUNTRY IN NUMBER)  RETURN VARCHAR2;
       PROCEDURE INSERT_COUNTRY(COUNTRY_NAME VARCHAR2);
       --PROCEDURE SET_ID_COUNTRY(NEW_VALUE NUMBER, OLD_VALUE NUMBER);
       PROCEDURE SET_NAME_COUNTRY(NEW_VALUE VARCHAR2, OLD_VALUE VARCHAR2);
END PKG_ADMIN_COUNTRY;


CREATE OR REPLACE PACKAGE BODY PKG_ADMIN_COUNTRY IS
        --FUNCTION GET_ID_COUNTRY IMPLEMENTATION
        FUNCTION GET_ID_COUNTRY(PNCOUNTRY_NAME IN VARCHAR2)  RETURN NUMBER
         IS
                  VNID_COUNTRY   NUMBER(10);
         BEGIN
                  SELECT ID_COUNTRY
                  INTO VNID_COUNTRY
                  FROM COUNTRY
                  WHERE COUNTRY_NAME=PNCOUNTRY_NAME;
                  RETURN (VNID_COUNTRY);
         END;

        -------------------------------------------------------------------------------
        --FUNCTION GET_NAME_COUNTRY IMPLEMENTATION
        FUNCTION GET_NAME_COUNTRY(PNID_COUNTRY IN NUMBER) RETURN VARCHAR2
        IS
                 VNNAME_COUNTRY VARCHAR2(50);

        BEGIN
                  SELECT COUNTRY_NAME
                  INTO VNNAME_COUNTRY
                  FROM COUNTRY
                  WHERE ID_COUNTRY=PNID_COUNTRY;
                  RETURN (VNNAME_COUNTRY);
        END;

        PROCEDURE INSERT_COUNTRY(COUNTRY_NAME VARCHAR2) is
         
           BEGIN
             INSERT INTO COUNTRY(ID_COUNTRY, COUNTRY_NAME)
             VALUES (s_country.nextval, COUNTRY_NAME);
             
           END INSERT_COUNTRY;
           
       ---------------------------------------------------------------------------------
       --PROCEDURE SET_ID_COUNTRY(NEW_VALUE NUMBER, OLD_VALUE NUMBER) IS
       --  BEGIN
       --      UPDATE COUNTRY SET ID_COUNTRY= NEW_VALUE WHERE ID_COUNTRY=OLD_VALUE;            
       --  END SET_ID_COUNTRY;
         
         
       ---------------------------------------------------------------------------------
       PROCEDURE SET_NAME_COUNTRY(NEW_VALUE VARCHAR2, OLD_VALUE VARCHAR2) IS
         BEGIN
             UPDATE COUNTRY SET COUNTRY_NAME= NEW_VALUE WHERE COUNTRY_NAME=OLD_VALUE;            
         END SET_NAME_COUNTRY;

END PKG_ADMIN_COUNTRY;
