alter table person add photo bfile;

update PERSON
       SET PHOTO=BFILENAME('IMAGES_PERFIL', 'Carlos.jpg') 
       WHERE PERSON.IDENTIFICATION='206745284';
       
update PERSON
       SET PHOTO=BFILENAME('IMAGES_PERFIL', 'Mayela.jpg') 
       WHERE PERSON.IDENTIFICATION='106760070';
       
update PERSON
       SET PHOTO=BFILENAME('IMAGES_PERFIL', 'Mario.jpg') 
       WHERE PERSON.IDENTIFICATION='136690451';
      
update PERSON
       SET PHOTO=BFILENAME('IMAGES_PERFIL', 'Angie.jpg') 
       WHERE PERSON.IDENTIFICATION='602547884';
       
update PERSON
       SET PHOTO=BFILENAME('IMAGES_PERFIL', 'Minor.jpg') 
       WHERE PERSON.IDENTIFICATION='108450931';
       
update PERSON
       SET PHOTO=BFILENAME('IMAGES_PERFIL', 'Maritza.jpg') 
       WHERE PERSON.IDENTIFICATION='108566974';
       
update PERSON
       SET PHOTO=BFILENAME('IMAGES_PERFIL', 'Karina.jpg') 
       WHERE PERSON.IDENTIFICATION='404542658';
       
update PERSON
       SET PHOTO=BFILENAME('IMAGES_PERFIL', 'Tatiana.jpg') 
       WHERE PERSON.IDENTIFICATION='105122554';
       
update PERSON
       SET PHOTO=BFILENAME('IMAGES_PERFIL', 'Luis.jpg') 
       WHERE PERSON.IDENTIFICATION='503216457';
       
update PERSON
       SET PHOTO=BFILENAME('IMAGES_PERFIL', 'Francisco.jpg') 
       WHERE PERSON.IDENTIFICATION='248579815';
