CREATE OR REPLACE PACKAGE PKG_ADMIN_PARAMETER  IS
       FUNCTION GET_ID_PARAMETER(PNID_PARAMETER IN NUMBER)  RETURN NUMBER;
       FUNCTION GET_NAME_PARAMETER(PNID_PARAMETER IN NUMBER)  RETURN VARCHAR2;
       FUNCTION GET_VALUE_PARAMETER(PNID_PARAMETER IN NUMBER)  RETURN VARCHAR2;
       PROCEDURE PROC_INSERT_PARAMETER(ID_PARAMETER NUMBER,NAME_PARAMETER VARCHAR2,VALUE_PARAMETER VARCHAR2);
       PROCEDURE SET_ID_PARAMETER(NEW_VALUE NUMBER, OLD_VALUE NUMBER);
       PROCEDURE SET_NAME_PARAMETER(NEW_VALUE VARCHAR2, OLD_VALUE VARCHAR2);
       PROCEDURE SET_VALUE_PARAMETER(NEW_VALUE VARCHAR2, OLD_VALUE VARCHAR2);
END PKG_ADMIN_PARAMETER;

CREATE OR REPLACE PACKAGE BODY PKG_ADMIN_PARAMETER IS
        --FUNCTION GET_ID_PARAMETER IMPLEMENTATION
        FUNCTION GET_ID_PARAMETER(PNID_PARAMETER IN NUMBER)  RETURN NUMBER
         IS
                  VNID_PARAMETER                      NUMBER(10);
         BEGIN
                  SELECT ID_PARAMETER
                  INTO VNID_PARAMETER
                  FROM PARAMETER
                  WHERE ID_PARAMETER=PNID_PARAMETER;
                  RETURN (VNID_PARAMETER);
         END;

        -------------------------------------------------------------------------------
        --FUNCTION GET_NAME_PARAMETER IMPLEMENTATION
        FUNCTION GET_NAME_PARAMETER(PNID_PARAMETER IN NUMBER) RETURN VARCHAR2
        IS
                 VNNAME_PARAMETER VARCHAR2(20);

        BEGIN
                  SELECT NAME_PARAMETER
                  INTO VNNAME_PARAMETER
                  FROM PARAMETER
                  WHERE ID_PARAMETER=PNID_PARAMETER;
                  RETURN (VNNAME_PARAMETER);
        END;

        -------------------------------------------------------------------------------
        --FUNCTION GET_VALUE_PARAMETER IMPLEMENTATION
        FUNCTION GET_VALUE_PARAMETER(PNID_PARAMETER IN NUMBER) RETURN VARCHAR2
        IS
                 VNVALUE_PARAMETER VARCHAR2(20);

        BEGIN
                  SELECT VALUE_PARAMETER
                  INTO VNVALUE_PARAMETER
                  FROM PARAMETER
                  WHERE ID_PARAMETER=PNID_PARAMETER;
                  RETURN (VNVALUE_PARAMETER);
        END;

        PROCEDURE PROC_INSERT_PARAMETER(ID_PARAMETER NUMBER,NAME_PARAMETER VARCHAR2,VALUE_PARAMETER VARCHAR2) IS
         
           BEGIN
             INSERT INTO PARAMETER(ID_PARAMETER,NAME_PARAMETER,VALUE_PARAMETER)
             VALUES (ID_PARAMETER,NAME_PARAMETER,VALUE_PARAMETER);
             
           END PROC_INSERT_PARAMETER;
           
           
           ---------------------------------------------------------------------------------
    PROCEDURE SET_ID_PARAMETER(NEW_VALUE NUMBER, OLD_VALUE NUMBER) IS
         BEGIN
             UPDATE PARAMETER SET ID_PARAMETER= NEW_VALUE WHERE ID_PARAMETER=OLD_VALUE;            
         END SET_ID_PARAMETER;
         
         
         ---------------------------------------------------------------------------------
    PROCEDURE SET_NAME_PARAMETER(NEW_VALUE VARCHAR2, OLD_VALUE VARCHAR2) IS
         BEGIN
             UPDATE PARAMETER SET NAME_PARAMETER= NEW_VALUE WHERE NAME_PARAMETER=OLD_VALUE;             
         END SET_NAME_PARAMETER;
         
         
         ---------------------------------------------------------------------------------
    PROCEDURE SET_VALUE_PARAMETER(NEW_VALUE VARCHAR2, OLD_VALUE VARCHAR2) IS
         BEGIN
             UPDATE PARAMETER SET VALUE_PARAMETER= NEW_VALUE WHERE VALUE_PARAMETER=OLD_VALUE;             
         END SET_VALUE_PARAMETER;
END PKG_ADMIN_PARAMETER;
