CREATE OR REPLACE PACKAGE PKG_ADMIN_TELEPHONE  IS
       FUNCTION GET_ID_PERSON(PNID_PERSON IN NUMBER)  RETURN NUMBER;
       FUNCTION GET_PHONE_NUMBER(PNID_PERSON IN NUMBER)  RETURN NUMBER;
       PROCEDURE PROC_INSERT_TELEPHONE(ID_PERSON NUMBER, PHONE_NUMBER NUMBER);
       PROCEDURE SET_ID_PERSON(NEW_VALUE NUMBER, OLD_VALUE NUMBER);
       PROCEDURE SET_PHONE_NUMBER(NEW_VALUE NUMBER, OLD_VALUE NUMBER);
END PKG_ADMIN_TELEPHONE;

CREATE OR REPLACE PACKAGE BODY PKG_ADMIN_TELEPHONE IS
        --FUNCTION GET_PHONE_NUMBER IMPLEMENTATION
        FUNCTION GET_PHONE_NUMBER(PNID_PERSON IN NUMBER)  RETURN NUMBER
         IS
                  VNPHONE_NUMBER                      NUMBER(10);
         BEGIN
                  SELECT PHONE_NUMBER
                  INTO VNPHONE_NUMBER
                  FROM TELEPHONE
                  WHERE ID_PERSON=PNID_PERSON;
                  RETURN (VNPHONE_NUMBER);
         END;

        -------------------------------------------------------------------------------
        --FUNCTION GET_ID_PERSON IMPLEMENTATION
        FUNCTION GET_ID_PERSON(PNID_PERSON IN NUMBER) RETURN NUMBER
        IS
                 VNID_PERSON NUMBER(20);

        BEGIN
                  SELECT ID_PERSON
                  INTO VNID_PERSON
                  FROM TELEPHONE
                  WHERE ID_PERSON=PNID_PERSON;
                  RETURN (VNID_PERSON);
        END;

        PROCEDURE PROC_INSERT_TELEPHONE(ID_PERSON NUMBER, PHONE_NUMBER NUMBER) IS
         
           BEGIN
             INSERT INTO TELEPHONE(ID_PERSON, PHONE_NUMBER)
             VALUES (ID_PERSON, PHONE_NUMBER);
             
           END PROC_INSERT_TELEPHONE;
           
           ---------------------------------------------------------------------------------
    PROCEDURE SET_ID_PERSON(NEW_VALUE NUMBER, OLD_VALUE NUMBER) IS
         BEGIN
             UPDATE TELEPHONE SET ID_PERSON= NEW_VALUE WHERE ID_PERSON=OLD_VALUE;             
         END SET_ID_PERSON;
         
         ---------------------------------------------------------------------------------
    PROCEDURE SET_PHONE_NUMBER(NEW_VALUE NUMBER, OLD_VALUE NUMBER) IS
         BEGIN
             UPDATE TELEPHONE SET PHONE_NUMBER= NEW_VALUE WHERE PHONE_NUMBER=OLD_VALUE;             
         END SET_PHONE_NUMBER;
END PKG_ADMIN_TELEPHONE;
