--CATEGORY_X_PERSON_ADMINISTRATOR PACKAGE IMPLEMENTATION
CREATE OR REPLACE PACKAGE PKG_ADMIN_CATEGORY_X_PERSON  IS
       FUNCTION GET_ID_PERSON(PNID_PERSON IN NUMBER)  RETURN NUMBER;
       FUNCTION GET_ID_CATEGORY(PNID_PERSON IN NUMBER)  RETURN NUMBER;
END PKG_ADMIN_CATEGORY_X_PERSON;

CREATE OR REPLACE PACKAGE BODY PKG_ADMIN_CATEGORY_X_PERSON IS
        --FUNCTION GET_ID_PERSON IMPLEMENTATION
        FUNCTION GET_ID_PERSON(PNID_PERSON IN NUMBER)  RETURN NUMBER
         IS
                  VNID_PERSON                        NUMBER(10);
         BEGIN
                  SELECT ID_PERSON 
                  INTO VNID_PERSON
                  FROM CATEGORY_X_PERSON
                  WHERE ID_PERSON=PNID_PERSON;
                  RETURN (VNID_PERSON);
         END;
         
        -------------------------------------------------------------------------------
        --FUNCTION GET_ID_CATEGORY IMPLEMENTATION
        FUNCTION GET_ID_CATEGORY(PNID_PERSON IN NUMBER) RETURN NUMBER
        IS
                 VNID_CATEGORY NUMBER(10);

        BEGIN
                  SELECT ID_CATEGORY
                  INTO VNID_CATEGORY
                  FROM CATEGORY_X_PERSON
                  WHERE ID_PERSON=PNID_PERSON;
                  RETURN (VNID_CATEGORY);
        END;

       
END PKG_ADMIN_CATEGORY_X_PERSON;
