--TELEPHONE_ADMINISTRATOR PACKAGE IMPLEMENTATION
CREATE OR REPLACE PACKAGE PKG_ADMIN_TELEPHONE  IS
       FUNCTION GET_ID_PERSON(PNID_PERSON IN NUMBER)  RETURN NUMBER;
       FUNCTION GET_PHONE_NUMBER(PNID_PERSON IN NUMBER)  RETURN NUMBER;
END PKG_ADMIN_TELEPHONE;

CREATE OR REPLACE PACKAGE BODY PKG_ADMIN_TELEPHONE IS
        --FUNCTION GET_ID_PERSON IMPLEMENTATION
        FUNCTION GET_PHONE_NUMBER(PNID_PERSON IN NUMBER)  RETURN NUMBER
         IS
                  VNPHONE_NUMBER                      NUMBER(10);
         BEGIN
                  SELECT PHONE_NUMBER  
                  INTO VNPHONE_NUMBER
                  FROM TELEPHONE
                  WHERE ID_PERSON=PNID_PERSON;
                  RETURN (VNPHONE_NUMBER);
         END;

        -------------------------------------------------------------------------------
        --FUNCTION GET_ID_CATEGORY IMPLEMENTATION
        FUNCTION GET_ID_PERSON(PNID_PERSON IN NUMBER) RETURN NUMBER
        IS
                 VNID_PERSON NUMBER(20);

        BEGIN
                  SELECT ID_PERSON
                  INTO VNID_PERSON
                  FROM TELEPHONE
                  WHERE ID_PERSON=PNID_PERSON;
                  RETURN (VNID_PERSON);
        END;

       
END PKG_ADMIN_TELEPHONE;
