CREATE OR REPLACE PACKAGE PKG_ADMIN_COMMUNITY  IS
       FUNCTION GET_ID_COMMUNITY(PNID_COMMUNITY IN NUMBER)  RETURN NUMBER;
       FUNCTION GET_ID_DISTRICT(PNID_COMMUNITY IN NUMBER)  RETURN NUMBER;
       FUNCTION GET_NAME_COMMUNITY(PNID_COMMUNITY IN NUMBER)  RETURN VARCHAR2;
       PROCEDURE PROC_INSERT_COMMUNITY(ID_COMMUNITY NUMBER,ID_DISTRICT NUMBER,NAME_COMMUNITY VARCHAR2);
       PROCEDURE SET_ID_COMMUNITY(NEW_VALUE NUMBER, OLD_VALUE NUMBER);
       PROCEDURE SET_ID_DISTRICT(NEW_VALUE NUMBER, OLD_VALUE NUMBER);
       PROCEDURE SET_NAME_COMMUNITY(NEW_VALUE VARCHAR2, OLD_VALUE VARCHAR2);
       
END PKG_ADMIN_COMMUNITY;


CREATE OR REPLACE PACKAGE BODY PKG_ADMIN_COMMUNITY IS
        --FUNCTION GET_ID_COMMUNITY IMPLEMENTATION
        FUNCTION GET_ID_COMMUNITY(PNID_COMMUNITY IN NUMBER)  RETURN NUMBER
         IS
                  VNID_COMMUNITY                      NUMBER(10);
         BEGIN
                  SELECT ID_COMMUNITY
                  INTO VNID_COMMUNITY
                  FROM COMMUNITY
                  WHERE ID_COMMUNITY=PNID_COMMUNITY;
                  RETURN (VNID_COMMUNITY);
         END;

        -------------------------------------------------------------------------------
        --FUNCTION GET_ID_DISTRICT IMPLEMENTATION
        FUNCTION GET_ID_DISTRICT(PNID_COMMUNITY IN NUMBER) RETURN NUMBER
        IS
                 VNID_DISTRICT                NUMBER(10);

        BEGIN
                  SELECT ID_DISTRICT
                  INTO VNID_DISTRICT
                  FROM COMMUNITY
                  WHERE ID_COMMUNITY=PNID_COMMUNITY;
                  RETURN (VNID_DISTRICT);
        END;

        -------------------------------------------------------------------------------
        --FUNCTION GET_NAME_COMMUNITY IMPLEMENTATION
        FUNCTION GET_NAME_COMMUNITY(PNID_COMMUNITY IN NUMBER) RETURN VARCHAR2
        IS
                 VNNAME_COMMUNITY DATE;

        BEGIN
                  SELECT NAME_COMMUNITY
                  INTO VNNAME_COMMUNITY
                  FROM COMMUNITY
                  WHERE ID_COMMUNITY=PNID_COMMUNITY;
                  RETURN (VNNAME_COMMUNITY);
        END;

        PROCEDURE PROC_INSERT_COMMUNITY(ID_COMMUNITY NUMBER,ID_DISTRICT NUMBER,NAME_COMMUNITY VARCHAR2) IS
         
           BEGIN
             INSERT INTO COMMUNITY(ID_COMMUNITY,ID_DISTRICT,NAME_COMMUNITY)
             VALUES (ID_COMMUNITY,ID_DISTRICT,NAME_COMMUNITY);
             
           END PROC_INSERT_COMMUNITY;
           
           
       PROCEDURE SET_ID_COMMUNITY(NEW_VALUE NUMBER, OLD_VALUE NUMBER) IS
         BEGIN
             UPDATE COMMUNITY SET ID_COMMUNITY= NEW_VALUE WHERE ID_COMMUNITY=OLD_VALUE;            
         END SET_ID_COMMUNITY;
         
         
       PROCEDURE SET_ID_DISTRICT(NEW_VALUE NUMBER, OLD_VALUE NUMBER) IS
         BEGIN
             UPDATE COMMUNITY SET ID_DISTRICT= NEW_VALUE WHERE ID_DISTRICT=OLD_VALUE;            
         END SET_ID_DISTRICT;
         
         
       PROCEDURE SET_NAME_COMMUNITY(NEW_VALUE VARCHAR2, OLD_VALUE VARCHAR2) IS
         BEGIN
             UPDATE COMMUNITY SET NAME_COMMUNITY= NEW_VALUE WHERE NAME_COMMUNITY=OLD_VALUE;            
         END SET_NAME_COMMUNITY;
         
         
END PKG_ADMIN_COMMUNITY;
