--NATIONALITY_ADMINISTRATOR PACKAGE IMPLEMENTATION
CREATE OR REPLACE PACKAGE PKG_ADMIN_NATIONALITY  IS
       FUNCTION GET_ID_NATIONALITY(PNID_NATIONALITY IN NUMBER)  RETURN NUMBER;
       FUNCTION GET_NAME_NATIONALITY(PNID_NATIONALITY IN NUMBER)  RETURN VARCHAR2;
END PKG_ADMIN_NATIONALITY;

CREATE OR REPLACE PACKAGE BODY PKG_ADMIN_NATIONALITY IS
        --FUNCTION GET_ID_PERSON IMPLEMENTATION
        FUNCTION GET_ID_NATIONALITY(PNID_NATIONALITY IN NUMBER)  RETURN NUMBER
         IS
                  VNID_NATIONALITY                      NUMBER(10);
         BEGIN
                  SELECT ID_NATIONALITY  
                  INTO VNID_NATIONALITY
                  FROM NATIONALITY
                  WHERE ID_NATIONALITY=PNID_NATIONALITY;
                  RETURN (VNID_NATIONALITY);
         END;

        -------------------------------------------------------------------------------
        --FUNCTION GET_ID_CATEGORY IMPLEMENTATION
        FUNCTION GET_NAME_NATIONALITY(PNID_NATIONALITY IN NUMBER) RETURN VARCHAR2
        IS
                 VNNAME_NATIONALITY VARCHAR(20);

        BEGIN
                  SELECT NAME_NATIONALITY
                  INTO VNNAME_NATIONALITY
                  FROM NATIONALITY
                  WHERE ID_NATIONALITY=PNID_NATIONALITY;
                  RETURN (VNNAME_NATIONALITY);
        END;

       
END PKG_ADMIN_NATIONALITY;
