CREATE OR REPLACE PACKAGE PKG_ADMIN_NATIONALITY_X_PERSON  IS
       FUNCTION GET_ID_NATIONALITY(PNID_PERSON IN VARCHAR2)  RETURN NUMBER;
       --FUNCTION GET_ID_PERSON(PNID_NATIONALITY IN NUMBER)  RETURN NUMBER;
       PROCEDURE INSERT_NATION_X_PERSON(ID_NATIONALITY NUMBER, ID_PERSON VARCHAR2);
       PROCEDURE SET_ID_NATIONALITY(PNNEW_VALUE NUMBER, PNOLD_VALUE NUMBER);
       --PROCEDURE SET_ID_PERSON(PNNEW_VALUE NUMBER, PNOLD_VALUE NUMBER);
END PKG_ADMIN_NATIONALITY_X_PERSON;


CREATE OR REPLACE PACKAGE BODY PKG_ADMIN_NATIONALITY_X_PERSON IS
        --FUNCTION GET_ID_PERSON IMPLEMENTATION
        FUNCTION GET_ID_NATIONALITY(PNID_PERSON IN VARCHAR2)  RETURN NUMBER
         IS
                 VMENERROR      EXCEPTION;
                  VNID_NATIONALITY  NUMBER(10);
         BEGIN
                  SELECT ID_NATIONALITY
                  INTO VNID_NATIONALITY
                  FROM NATIONALITY_X_PERSON
                  WHERE ID_PERSON=PNID_PERSON;
                  RETURN (VNID_NATIONALITY);
                 EXCEPTION 
                         WHEN TOO_MANY_ROWS THEN
                           DBMS_OUTPUT.PUT_LINE('YOUR SELECTION RETURNS MORE THAN ONE RESULT.');
                         WHEN NO_DATA_FOUND THEN
                           DBMS_OUTPUT.PUT_LINE('THE ELEMENT DOES NOT EXIST IN THE DATABASE.');
                         WHEN OTHERS THEN
                           DBMS_OUTPUT.PUT_LINE('ERROR');
         END;

        -------------------------------------------------------------------------------
        --FUNCTION GET_ID_CATEGORY IMPLEMENTATION
        --FUNCTION GET_ID_PERSON(PNID_NATIONALITY IN NUMBER) RETURN NUMBER
        --IS
        --         VNID_PERSON NUMBER(20);

        --BEGIN
        --          SELECT ID_PERSON
        --          INTO VNID_PERSON
        --          FROM NATIONALITY_X_PERSON
        --          WHERE ID_NATIONALITY=PNID_NATIONALITY;
        --          RETURN (VNID_PERSON);
        --END;

        PROCEDURE INSERT_NATION_X_PERSON(ID_NATIONALITY NUMBER, ID_PERSON VARCHAR2) IS
      VMENERROR                              EXCEPTION;

           BEGIN
             INSERT INTO NATIONALITY_X_PERSON(ID_NATIONALITY, ID_PERSON)
             VALUES (ID_NATIONALITY, ID_PERSON);
             IF SQL%NOTFOUND THEN
                    RAISE VMENERROR;
            END IF;
            EXCEPTION 
               WHEN VMENERROR THEN
                 DBMS_OUTPUT.PUT_LINE('THE ELEMENT DOES NOT EXIST IN THE DATABASE.');
               WHEN DUP_VAL_ON_INDEX THEN
                 DBMS_OUTPUT.PUT_LINE('THE ELEMENT IS ALREADY IN THE DATABASE.');

           END INSERT_NATION_X_PERSON;


        ---------------------------------------------------------------------------------
    PROCEDURE SET_ID_NATIONALITY(PNNEW_VALUE NUMBER, PNOLD_VALUE NUMBER) IS
      VMENERROR                              EXCEPTION;
         BEGIN
             UPDATE NATIONALITY_X_PERSON SET ID_NATIONALITY= PNNEW_VALUE WHERE ID_NATIONALITY=PNOLD_VALUE;
             IF SQL%NOTFOUND THEN
                    RAISE VMENERROR;
            END IF;
            EXCEPTION 
               WHEN VMENERROR THEN
                 DBMS_OUTPUT.PUT_LINE('THE ELEMENT DOES NOT EXIST IN THE DATABASE.');
               WHEN DUP_VAL_ON_INDEX THEN
                 DBMS_OUTPUT.PUT_LINE('THE ELEMENT IS ALREADY IN THE DATABASE.');
         END SET_ID_NATIONALITY;


         ---------------------------------------------------------------------------------
    --PROCEDURE SET_ID_PERSON(PNNEW_VALUE NUMBER, PNOLD_VALUE NUMBER) IS
    --     BEGIN
    --         UPDATE NATIONALITY_X_PERSON SET ID_PERSON= PNNEW_VALUE WHERE ID_PERSON=PNOLD_VALUE;
    --     END SET_ID_PERSON;
END PKG_ADMIN_NATIONALITY_X_PERSON;
