--CATEGORY_FAV_ADMINISTRATOR PACKAGE IMPLEMENTATION
CREATE OR REPLACE PACKAGE PKG_ADMIN_CATEGORY_FAV  IS
       FUNCTION GET_ID_CATEGORY_FAV(PNID_CATEGORY_FAV IN NUMBER)  RETURN NUMBER;
       FUNCTION GET_NAME_CATEGORY(PNID_CATEGORY_FAV IN NUMBER)  RETURN VARCHAR2;
END PKG_ADMIN_CATEGORY_FAV;

CREATE OR REPLACE PACKAGE BODY PKG_ADMIN_CATEGORY_FAV IS
        --FUNCTION GET_ID_CATEGORY_FAV IMPLEMENTATION
        FUNCTION GET_ID_CATEGORY_FAV(PNID_CATEGORY_FAV IN NUMBER)  RETURN NUMBER
         IS
                  VNID_CATEGORY_FAV                        NUMBER(10);
         BEGIN
                  SELECT ID_CATEGORY_FAV 
                  INTO VNID_CATEGORY_FAV
                  FROM CATEGORY_FAV
                  WHERE ID_CATEGORY_FAV=PNID_CATEGORY_FAV;
                  RETURN (VNID_CATEGORY_FAV);
         END;
         
        -------------------------------------------------------------------------------
        --FUNCTION GET_NAME_CATEGORY IMPLEMENTATION
        FUNCTION GET_NAME_CATEGORY(PNID_CATEGORY_FAV IN NUMBER) RETURN VARCHAR2
        IS
                 VNNAME_CATEGORY_FAV VARCHAR2;

        BEGIN
                  SELECT NAME_CATEGORY
                  INTO VNNAME_CATEGORY_FAV
                  FROM CATEGORY_FAV
                  WHERE ID_CATEGORY_FAV=PNID_CATEGORY_FAV;
                  RETURN (VNNAME_CATEGORY_FAV);
        END;

       
END PKG_ADMIN_CATEGORY_FAV;
