CREATE OR REPLACE PACKAGE PKG_ADMIN_PROPOSAL_X_CATEGORY IS
       FUNCTION GET_ID_CATEGORY_FAV(PNID_PROPOSAL IN NUMBER)  RETURN NUMBER;
       FUNCTION GET_ID_PROPOSAL(PNID_PROPOSAL IN NUMBER)  RETURN NUMBER;
       PROCEDURE PROC_INSERT_PROP_X_CATEGORY(ID_PROPOSAL NUMBER, ID_CATEGORY_FAV NUMBER);
       PROCEDURE GET_ID_CATEGORY_FAV(NEW_VALUE NUMBER, OLD_VALUE NUMBER);
       PROCEDURE GET_ID_PROPOSAL(NEW_VALUE NUMBER, OLD_VALUE NUMBER);

END PKG_ADMIN_PROPOSAL_X_CATEGORY;

CREATE OR REPLACE PACKAGE BODY PKG_ADMIN_PROPOSAL_X_CATEGORY IS
        --FUNCTION GET_ID_CATEGORY_FAV IMPLEMENTATION
        FUNCTION GET_ID_CATEGORY_FAV(PNID_PROPOSAL IN NUMBER)  RETURN NUMBER
         IS
                  VNID_CATEGORY_FAV                     NUMBER(10);
         BEGIN
                  SELECT ID_CATEGORY_FAV
                  INTO VNID_CATEGORY_FAV
                  FROM PROPOSAL_X_CATEGORY
                  WHERE ID_PROPOSAL=PNID_PROPOSAL;
                  RETURN (VNID_CATEGORY_FAV);
         END;

        -------------------------------------------------------------------------------
        --FUNCTION GET_ID_PROPOSAL IMPLEMENTATION
        FUNCTION GET_ID_PROPOSAL(PNID_PROPOSAL IN NUMBER) RETURN NUMBER
        IS
                 VNID_PROPOSAL NUMBER(20);

        BEGIN
                  SELECT ID_PROPOSAL
                  INTO VNID_PROPOSAL
                  FROM PROPOSAL_X_CATEGORY
                  WHERE ID_PROPOSAL=PNID_PROPOSAL;
                  RETURN (VNID_PROPOSAL);
        END;

        PROCEDURE PROC_INSERT_PROP_X_CATEGORY(ID_PROPOSAL NUMBER, ID_CATEGORY_FAV NUMBER) IS
         
           BEGIN
             INSERT INTO PROPOSAL_X_CATEGORY(ID_PROPOSAL, ID_CATEGORY_FAV)
             VALUES (ID_PROPOSAL, ID_CATEGORY_FAV);
             
           END PROC_INSERT_PROP_X_CATEGORY;
           
           
           ---------------------------------------------------------------------------------
    PROCEDURE GET_ID_CATEGORY_FAV(NEW_VALUE NUMBER, OLD_VALUE NUMBER) IS
         BEGIN
             UPDATE PROPOSAL_X_CATEGORY SET ID_CATEGORY_FAV= NEW_VALUE WHERE ID_CATEGORY_FAV=OLD_VALUE;             
         END GET_ID_CATEGORY_FAV;
         
         
         ---------------------------------------------------------------------------------
    PROCEDURE GET_ID_PROPOSAL(NEW_VALUE NUMBER, OLD_VALUE NUMBER) IS
         BEGIN
             UPDATE PROPOSAL_X_CATEGORY SET ID_PROPOSAL= NEW_VALUE WHERE ID_PROPOSAL=OLD_VALUE;             
         END GET_ID_PROPOSAL;
END PKG_ADMIN_PROPOSAL_X_CATEGORY;
