CREATE OR REPLACE PACKAGE PKG_ADMIN_COMMENT_PROP  IS
       FUNCTION GET_ID_COMMENT(PNID_COMMENT IN NUMBER)  RETURN NUMBER;
       FUNCTION GET_DESCRIPTION_COMMENT(PNID_COMMENT IN NUMBER)  RETURN VARCHAR2;
       FUNCTION GET_DATE_COMMENT(PNID_COMMENT IN NUMBER)  RETURN DATE;
       PROCEDURE PROC_INSERT_COMMENT_PROP(ID_COMMENT NUMBER,DESCRIPTION_COMMENT VARCHAR2,DATE_COMMENT DATE);
       PROCEDURE SET_ID_COMMENT(NEW_VALUE NUMBER, OLD_VALUE NUMBER);
       PROCEDURE SET_DESCRIPTION_COMMENT(NEW_VALUE VARCHAR2, OLD_VALUE VARCHAR2);
       PROCEDURE SET_DATE_COMMENT(NEW_VALUE DATE, OLD_VALUE DATE);

END PKG_ADMIN_COMMENT_PROP;

CREATE OR REPLACE PACKAGE BODY PKG_ADMIN_COMMENT_PROP IS
        --FUNCTION GET_ID_PERSON IMPLEMENTATION
        FUNCTION GET_ID_COMMENT(PNID_COMMENT IN NUMBER)  RETURN NUMBER
         IS
                  VNID_COMMENT                        NUMBER(10);
         BEGIN
                  SELECT ID_COMMENT
                  INTO VNID_COMMENT
                  FROM COMMENT_PROP
                  WHERE ID_COMMENT=PNID_COMMENT;
                  RETURN (VNID_COMMENT);
         END;

        -------------------------------------------------------------------------------
        --FUNCTION GET_DESCRIPTION_COMMENT IMPLEMENTATION
        FUNCTION GET_DESCRIPTION_COMMENT(PNID_COMMENT IN NUMBER) RETURN VARCHAR2
        IS
                 VNDESCRIPTION_COMMENT                VARCHAR2(50);

        BEGIN
                  SELECT DESCRIPTION_COMMENT
                  INTO VNDESCRIPTION_COMMENT
                  FROM COMMENT_PROP
                  WHERE ID_COMMENT=PNID_COMMENT;
                  RETURN (VNDESCRIPTION_COMMENT);
        END;

        -------------------------------------------------------------------------------
        --FUNCTION GET_DATE_COMMENT IMPLEMENTATION
        FUNCTION GET_DATE_COMMENT(PNID_COMMENT IN NUMBER) RETURN DATE
        IS
                 VNDATE_COMMENT DATE;

        BEGIN
                  SELECT DATE_COMMENT
                  INTO VNDATE_COMMENT
                  FROM COMMENT_PROP
                  WHERE ID_COMMENT=PNID_COMMENT;
                  RETURN (VNDATE_COMMENT);
        END;
        
        PROCEDURE PROC_INSERT_COMMENT_PROP(ID_COMMENT NUMBER,DESCRIPTION_COMMENT VARCHAR2,DATE_COMMENT DATE) IS
         
           BEGIN
             INSERT INTO COMMENT_PROP(ID_COMMENT,DESCRIPTION_COMMENT,DATE_COMMENT)
             VALUES (ID_COMMENT,DESCRIPTION_COMMENT,DATE_COMMENT);
             
           END PROC_INSERT_COMMENT_PROP;
           
           
       PROCEDURE SET_ID_COMMENT(NEW_VALUE NUMBER, OLD_VALUE NUMBER) IS
         BEGIN
             UPDATE COMMENT_PROP SET ID_COMMENT= NEW_VALUE WHERE ID_COMMENT=OLD_VALUE;             
         END SET_ID_COMMENT;
         
         
       PROCEDURE SET_DESCRIPTION_COMMENT(NEW_VALUE VARCHAR2, OLD_VALUE VARCHAR2) IS
         BEGIN
             UPDATE COMMENT_PROP SET DESCRIPTION_COMMENT= NEW_VALUE WHERE DESCRIPTION_COMMENT=OLD_VALUE; 
         END SET_DESCRIPTION_COMMENT;
         
         
      PROCEDURE SET_DATE_COMMENT(NEW_VALUE DATE, OLD_VALUE DATE) IS
         BEGIN
             UPDATE COMMENT_PROP SET DATE_COMMENT= NEW_VALUE WHERE DATE_COMMENT=OLD_VALUE;             
         END SET_DATE_COMMENT;
END PKG_ADMIN_COMMENT_PROP;
