--NATIONALITY_X_PERSON_ADMINISTRATOR PACKAGE IMPLEMENTATION
CREATE OR REPLACE PACKAGE PKG_ADMIN_NATIONALITY_X_PERSON  IS
       FUNCTION GET_ID_NATIONALITY(PNID_NATIONALITY IN NUMBER)  RETURN NUMBER;
       FUNCTION GET_ID_PERSON(PNID_NATIONALITY IN NUMBER)  RETURN NUMBER;
END PKG_ADMIN_NATIONALITY_X_PERSON;

CREATE OR REPLACE PACKAGE BODY PKG_ADMIN_NATIONALITY_X_PERSON IS
        --FUNCTION GET_ID_PERSON IMPLEMENTATION
        FUNCTION GET_ID_NATIONALITY(PNID_NATIONALITY IN NUMBER)  RETURN NUMBER
         IS
                  VNID_NATIONALITY                      NUMBER(10);
         BEGIN
                  SELECT ID_NATIONALITY  
                  INTO VNID_NATIONALITY
                  FROM NATIONALITY_X_PERSON
                  WHERE ID_NATIONALITY=PNID_NATIONALITY;
                  RETURN (VNID_NATIONALITY);
         END;

        -------------------------------------------------------------------------------
        --FUNCTION GET_ID_CATEGORY IMPLEMENTATION
        FUNCTION GET_ID_PERSON(PNID_NATIONALITY IN NUMBER) RETURN NUMBER
        IS
                 VNID_PERSON NUMBER(20);

        BEGIN
                  SELECT ID_PERSON
                  INTO VNID_PERSON
                  FROM NATIONALITY_X_PERSON
                  WHERE ID_NATIONALITY=PNID_NATIONALITY;
                  RETURN (VNID_PERSON);
        END;

       
END PKG_ADMIN_NATIONALITY_X_PERSON;
