--PARAMETER_ADMINISTRATOR PACKAGE IMPLEMENTATION
CREATE OR REPLACE PACKAGE PKG_ADMIN_PARAMETER  IS
       FUNCTION GET_ID_PARAMETER(PNID_PARAMETER IN NUMBER)  RETURN NUMBER;
       FUNCTION GET_NAME_PARAMETER(PNID_PARAMETER IN NUMBER)  RETURN VARCHAR2;
       FUNCTION GET_VALUE_PARAMETER(PNID_PARAMETER IN NUMBER)  RETURN VARCHAR2;
END PKG_ADMIN_PARAMETER;

CREATE OR REPLACE PACKAGE BODY PKG_ADMIN_PARAMETER IS
        --FUNCTION GET_ID_PERSON IMPLEMENTATION
        FUNCTION GET_ID_PARAMETER(PNID_PARAMETER IN NUMBER)  RETURN NUMBER
         IS
                  VNID_PARAMETER                      NUMBER(10);
         BEGIN
                  SELECT ID_PARAMETER  
                  INTO VNID_PARAMETER
                  FROM PARAMETER
                  WHERE ID_PARAMETER=PNID_PARAMETER;
                  RETURN (VNID_PARAMETER);
         END;

        -------------------------------------------------------------------------------
        --FUNCTION GET_ID_CATEGORY IMPLEMENTATION
        FUNCTION GET_NAME_PARAMETER(PNID_PARAMETER IN NUMBER) RETURN VARCHAR2
        IS
                 VNNAME_PARAMETER VARCHAR2(20);

        BEGIN
                  SELECT NAME_PARAMETER
                  INTO VNNAME_PARAMETER
                  FROM PARAMETER
                  WHERE ID_PARAMETER=PNID_PARAMETER;
                  RETURN (VNNAME_PARAMETER);
        END;
        
        -------------------------------------------------------------------------------
        --FUNCTION GET_ID_CATEGORY IMPLEMENTATION
        FUNCTION GET_VALUE_PARAMETER(PNID_PARAMETER IN NUMBER) RETURN VARCHAR2
        IS
                 VNVALUE_PARAMETER VARCHAR2(20);

        BEGIN
                  SELECT VALUE_PARAMETER
                  INTO VNVALUE_PARAMETER
                  FROM PARAMETER
                  WHERE ID_PARAMETER=PNID_PARAMETER;
                  RETURN (VNVALUE_PARAMETER);
        END;

       
END PKG_ADMIN_PARAMETER;
