CREATE OR REPLACE PACKAGE PKG_ADMIN_PERSON  IS
       --FUNCTION GET_ID_PERSON(PNname IN NUMBER)  RETURN NUMBER;
       FUNCTION GET_ID_COMMUNITY(PNIDENTIFICATION IN VARCHAR2)  RETURN NUMBER;
       FUNCTION GET_NAME_PERSON(PNIDENTIFICATION IN VARCHAR2)  RETURN VARCHAR2;
       FUNCTION GET_FIRST_LAST_NAME(PNIDENTIFICATION IN VARCHAR2)  RETURN VARCHAR2;
       FUNCTION GET_BIRTHDATE(PNIDENTIFICATION IN VARCHAR2)  RETURN DATE;
       FUNCTION GET_SECOND_LAST_NAME(PNIDENTIFICATION IN VARCHAR2)  RETURN VARCHAR2;
       PROCEDURE INSERT_PERSON(PNIDENTIFICATION VARCHAR2,PNNAME VARCHAR2,
       PNFIRST_LAST_NAME VARCHAR2,PNSECOND_LAST_NAME VARCHAR2,PNBIRTHDATE DATE, PNID_COMMUNITY NUMBER);
       PROCEDURE SET_ID_PERSON(PNNEW_VALUE VARCHAR2, PNOLD_VALUE VARCHAR2);
       PROCEDURE SET_ID_COMMUNITY(PNNEW_VALUE NUMBER, PNOLD_VALUE NUMBER);
       PROCEDURE SET_NAME_PERSON(PNNEW_VALUE VARCHAR2, PNOLD_VALUE VARCHAR2);
       PROCEDURE SET_FIRST_LAST_NAME(PNNEW_VALUE VARCHAR2, PNOLD_VALUE VARCHAR2);
       PROCEDURE SET_BIRTHDATE(PNNEW_VALUE DATE, PNOLD_VALUE DATE);
       PROCEDURE SET_SECOND_LAST_NAME(PNNEW_VALUE VARCHAR2, PNOLD_VALUE VARCHAR2);
END PKG_ADMIN_PERSON;

CREATE OR REPLACE PACKAGE BODY PKG_ADMIN_PERSON IS
        --FUNCTION GET_ID_PERSON IMPLEMENTATION
        --FUNCTION GET_ID_PERSON(PNNAME IN NUMBER)  RETURN NUMBER
         --IS
           --       VNID_PERSON                      NUMBER(10);
         --BEGIN
          --        SELECT ID_PERSON
          --        INTO VNID_PERSON
          --        FROM PERSON
          --        WHERE ID_PERSON=PNID_PERSON;
          --        RETURN (VNID_PERSON);
         --END;

        -------------------------------------------------------------------------------
        --FUNCTION GET_ID_COMMUNITY IMPLEMENTATION
        FUNCTION GET_ID_COMMUNITY(PNIDENTIFICATION IN VARCHAR2) RETURN NUMBER
        IS
                 VNID_COMMUNITY NUMBER(20);

        BEGIN
                  SELECT ID_COMMUNITY
                  INTO VNID_COMMUNITY
                  FROM PERSON
                  WHERE IDENTIFICATION=PNIDENTIFICATION;
                  RETURN (VNID_COMMUNITY);
        END;

        -------------------------------------------------------------------------------
        --FUNCTION GET_NAME_PERSON IMPLEMENTATION
        FUNCTION GET_NAME_PERSON(PNIDENTIFICATION IN VARCHAR2) RETURN VARCHAR2
        IS
                 VNNAME_PERSON VARCHAR2(50);

        BEGIN
                  SELECT NAME
                  INTO VNNAME_PERSON
                  FROM PERSON
                  WHERE IDENTIFICATION=PNIDENTIFICATION;
                  RETURN (VNNAME_PERSON);
        END;

        -------------------------------------------------------------------------------
        --FUNCTION GET_FIRST_LAST_NAME IMPLEMENTATION
        FUNCTION GET_FIRST_LAST_NAME(PNIDENTIFICATION IN VARCHAR2) RETURN VARCHAR2
        IS
                 VNFIRST_LAST_NAME VARCHAR2(50);

        BEGIN
                  SELECT FIRST_LAST_NAME
                  INTO VNFIRST_LAST_NAME
                  FROM PERSON
                  WHERE IDENTIFICATION=PNIDENTIFICATION;
                  RETURN (VNFIRST_LAST_NAME);
        END;

        -------------------------------------------------------------------------------
        --FUNCTION GET_BIRTHDATE IMPLEMENTATION
        FUNCTION GET_BIRTHDATE(PNIDENTIFICATION IN VARCHAR2) RETURN DATE
        IS
                 VNBIRTHDATE DATE;

        BEGIN
                  SELECT BIRTHDATE
                  INTO VNBIRTHDATE
                  FROM PERSON
                  WHERE IDENTIFICATION=PNIDENTIFICATION;
                  RETURN (VNBIRTHDATE);
        END;

        -------------------------------------------------------------------------------
        --FUNCTION GET_SECOND_LAST_NAME IMPLEMENTATION
        FUNCTION GET_SECOND_LAST_NAME(PNIDENTIFICATION IN VARCHAR2) RETURN VARCHAR2
        IS
                 VNSECOND_LAST_NAME VARCHAR2(50);

        BEGIN
                  SELECT SECOND_LAST_NAME
                  INTO VNSECOND_LAST_NAME
                  FROM PERSON
                  WHERE IDENTIFICATION=PNIDENTIFICATION;
                  RETURN (VNSECOND_LAST_NAME);
        END;

        PROCEDURE INSERT_PERSON(PNIDENTIFICATION VARCHAR2,PNNAME  VARCHAR2,PNFIRST_LAST_NAME VARCHAR2,
                 PNSECOND_LAST_NAME VARCHAR2,PNBIRTHDATE DATE, PNID_COMMUNITY NUMBER) IS
         
           BEGIN
             INSERT INTO PERSON(IDENTIFICATION,NAME,FIRST_LAST_NAME,SECOND_LAST_NAME,BIRTHDATE,ID_COMMUNITY)
             VALUES (PNIDENTIFICATION,PNNAME,PNFIRST_LAST_NAME,PNSECOND_LAST_NAME, PNBIRTHDATE,PNID_COMMUNITY);
             
           END INSERT_PERSON;
           
           ---------------------------------------------------------------------------------
    PROCEDURE SET_ID_PERSON(PNNEW_VALUE VARCHAR2, PNOLD_VALUE VARCHAR2) IS
         BEGIN
             UPDATE PERSON SET IDENTIFICATION= PNNEW_VALUE WHERE IDENTIFICATION=PNOLD_VALUE;             
         END SET_ID_PERSON;
         
         ---------------------------------------------------------------------------------
    PROCEDURE SET_ID_COMMUNITY(PNNEW_VALUE NUMBER, PNOLD_VALUE NUMBER) IS
         BEGIN
             UPDATE PERSON SET ID_COMMUNITY= PNNEW_VALUE WHERE ID_COMMUNITY=PNOLD_VALUE;             
         END SET_ID_COMMUNITY;
         
         ---------------------------------------------------------------------------------
    PROCEDURE SET_NAME_PERSON(PNNEW_VALUE VARCHAR2, PNOLD_VALUE VARCHAR2) IS
         BEGIN
            UPDATE PERSON SET NAME= PNNEW_VALUE WHERE NAME=PNOLD_VALUE;             
         END SET_NAME_PERSON;
         
         ---------------------------------------------------------------------------------
    PROCEDURE SET_FIRST_LAST_NAME(PNNEW_VALUE VARCHAR2, PNOLD_VALUE VARCHAR2) IS
         BEGIN
             UPDATE PERSON SET FIRST_LAST_NAME= PNNEW_VALUE WHERE FIRST_LAST_NAME=PNOLD_VALUE;             
         END SET_FIRST_LAST_NAME;
         
         ---------------------------------------------------------------------------------
    PROCEDURE SET_BIRTHDATE(PNNEW_VALUE DATE, PNOLD_VALUE DATE) IS
         BEGIN
             UPDATE PERSON SET BIRTHDATE= PNNEW_VALUE WHERE BIRTHDATE=PNOLD_VALUE;             
         END SET_BIRTHDATE;
         
         ---------------------------------------------------------------------------------
    PROCEDURE SET_SECOND_LAST_NAME(PNNEW_VALUE VARCHAR2, PNOLD_VALUE VARCHAR2) IS
         BEGIN
             UPDATE PERSON SET SECOND_LAST_NAME= PNNEW_VALUE WHERE SECOND_LAST_NAME=PNOLD_VALUE;             
         END SET_SECOND_LAST_NAME;
         
         
END PKG_ADMIN_PERSON;
