CREATE OR REPLACE PACKAGE PKG_ADMIN_VOTE IS
       --FUNCTION GET_ID_PERSON(PNID_PERSON IN NUMBER)  RETURN NUMBER;
       --FUNCTION GET_ID_PROPOSAL(PNID_PERSON IN NUMBER)  RETURN NUMBER;
       PROCEDURE INSERT_VOTE(PNID_PROPOSAL NUMBER, PNID_PERSON VARCHAR2);
       --PROCEDURE GET_ID_PERSON(PNNEW_VALUE NUMBER, PNOLD_VALUE NUMBER);
       --PROCEDURE GET_ID_PROPOSAL(PNNEW_VALUE NUMBER, PNOLD_VALUE NUMBER);
END PKG_ADMIN_VOTE;


CREATE OR REPLACE PACKAGE BODY PKG_ADMIN_VOTE IS
        --FUNCTION GET_ID_PERSON IMPLEMENTATION
        --FUNCTION GET_ID_PERSON(PNID_PERSON IN NUMBER)  RETURN NUMBER
        -- IS
        --          VNID_PERSON                      NUMBER(10);
        -- BEGIN
        --          SELECT ID_PERSON
        --          INTO VNID_PERSON
        --          FROM VOTE
        --          WHERE ID_PERSON=PNID_PERSON;
        --          RETURN (VNID_PERSON);
        -- END;

        -------------------------------------------------------------------------------
        --FUNCTION GET_ID_PROPOSAL IMPLEMENTATION
        --FUNCTION GET_ID_PROPOSAL(PNID_PERSON IN NUMBER) RETURN NUMBER
        --IS
        --         VNID_PROPOSAL NUMBER(20);

        --BEGIN
        --          SELECT ID_PROPOSAL
        --          INTO VNID_PROPOSAL
        --          FROM VOTE
        --          WHERE ID_PERSON=PNID_PERSON;
        --         RETURN (VNID_PROPOSAL);
       -- END;

        PROCEDURE INSERT_VOTE(PNID_PROPOSAL NUMBER, PNID_PERSON VARCHAR2) IS

           BEGIN
             INSERT INTO VOTE(ID_PROPOSAL, ID_PERSON)
             VALUES (PNID_PROPOSAL, PNID_PERSON);
             UPDATE PROPOSAL SET VOTE= ((SELECT VOTE FROM PROPOSAL WHERE ID_PROPOSAL=PNID_PROPOSAL)+1)
                    WHERE ID_PROPOSAL=PNID_PROPOSAL;

           END INSERT_VOTE;

           ---------------------------------------------------------------------------------
    --PROCEDURE GET_ID_PERSON(PNNEW_VALUE NUMBER, PNOLD_VALUE NUMBER) IS
    --     BEGIN
    --        UPDATE VOTE SET ID_PERSON= PNNEW_VALUE WHERE ID_PERSON=PNOLD_VALUE;
    --     END GET_ID_PERSON;

         ---------------------------------------------------------------------------------
    --PROCEDURE GET_ID_PROPOSAL(PNNEW_VALUE NUMBER, PNOLD_VALUE NUMBER) IS
    --     BEGIN
    --         UPDATE VOTE SET ID_PROPOSAL= PNNEW_VALUE WHERE ID_PROPOSAL=PNOLD_VALUE;
    --     END GET_ID_PROPOSAL;
END PKG_ADMIN_VOTE;
