CREATE OR REPLACE PACKAGE PKG_ADMIN_TELEPHONE  IS
       FUNCTION GET_ID_PERSON(PNTELEPHONE IN VARCHAR2)  RETURN VARCHAR2;
       FUNCTION GET_PHONE_NUMBER(PNIDENTIFICATION IN VARCHAR2)  RETURN VARCHAR2;
       PROCEDURE INSERT_TELEPHONE(PNTELEPHONE VARCHAR2, PNIDENTIFICATION VARCHAR2);
       PROCEDURE SET_ID_PERSON(PNNEW_VALUE VARCHAR2, PNOLD_VALUE VARCHAR2);
       PROCEDURE SET_PHONE_NUMBER(PNNEW_VALUE VARCHAR2, PNOLD_VALUE VARCHAR2);
END PKG_ADMIN_TELEPHONE;

CREATE OR REPLACE PACKAGE BODY PKG_ADMIN_TELEPHONE IS
        --FUNCTION GET_PHONE_NUMBER IMPLEMENTATION
        FUNCTION GET_PHONE_NUMBER(PNIDENTIFICATION IN VARCHAR2)  RETURN VARCHAR2
         IS
                  VNPHONE_NUMBER   VARCHAR2(15);
         BEGIN
                  SELECT TELEPHONE
                  INTO VNPHONE_NUMBER
                  FROM TELEPHONE
                  WHERE IDENTIFICATION=PNIDENTIFICATION;
                  RETURN (VNPHONE_NUMBER);
         END;

        -------------------------------------------------------------------------------
        --FUNCTION GET_ID_PERSON IMPLEMENTATION
        FUNCTION GET_ID_PERSON(PNTELEPHONE IN VARCHAR2) RETURN VARCHAR2
        IS
                 VNID_PERSON VARCHAR2(20);

        BEGIN
                  SELECT IDENTIFICATION
                  INTO VNID_PERSON
                  FROM TELEPHONE
                  WHERE TELEPHONE=PNTELEPHONE;
                  RETURN (VNID_PERSON);
        END;

        PROCEDURE INSERT_TELEPHONE(PNTELEPHONE VARCHAR2, PNIDENTIFICATION VARCHAR2) IS
         
           BEGIN
             INSERT INTO TELEPHONE(TELEPHONE,IDENTIFICATION)
             VALUES (PNTELEPHONE,PNIDENTIFICATION);
             
           END INSERT_TELEPHONE;
           
           ---------------------------------------------------------------------------------
    PROCEDURE SET_ID_PERSON(PNNEW_VALUE VARCHAR2, PNOLD_VALUE VARCHAR2) IS
         BEGIN
             UPDATE TELEPHONE SET IDENTIFICATION= PNNEW_VALUE WHERE IDENTIFICATION=PNOLD_VALUE;             
         END SET_ID_PERSON;
         
         ---------------------------------------------------------------------------------
    PROCEDURE SET_PHONE_NUMBER(PNNEW_VALUE VARCHAR2, PNOLD_VALUE VARCHAR2) IS
         BEGIN
             UPDATE TELEPHONE SET TELEPHONE= PNNEW_VALUE WHERE TELEPHONE=PNOLD_VALUE;             
         END SET_PHONE_NUMBER;
END PKG_ADMIN_TELEPHONE;
