CREATE OR REPLACE PACKAGE PKG_ADMIN_DISTRICT  IS
       FUNCTION GET_ID_DISTRICT(PNID_DISTRICT IN NUMBER)  RETURN NUMBER;
       FUNCTION GET_ID_CANTON(PNID_DISTRICT IN NUMBER)  RETURN NUMBER;
       FUNCTION GET_NAME_DISTRICT(PNID_DISTRICT IN NUMBER)  RETURN VARCHAR2;
       PROCEDURE PROC_INSERT_DISTRICT(ID_DISTRICT NUMBER,ID_CANTON NUMBER,NAME_DISTRICT VARCHAR2);
       PROCEDURE SET_ID_DISTRICT(NEW_VALUE NUMBER, OLD_VALUE NUMBER);
       PROCEDURE SET_ID_CANTON(NEW_VALUE NUMBER, OLD_VALUE NUMBER);
       PROCEDURE SET_NAME_DISTRICT(NEW_VALUE VARCHAR2, OLD_VALUE VARCHAR2);
END PKG_ADMIN_DISTRICT;

CREATE OR REPLACE PACKAGE BODY PKG_ADMIN_DISTRICT IS
        --FUNCTION GET_ID_DISTRICT IMPLEMENTATION
        FUNCTION GET_ID_DISTRICT(PNID_DISTRICT IN NUMBER)  RETURN NUMBER
         IS
                  VNID_DISTRICT                      NUMBER(10);
         BEGIN
                  SELECT ID_DISTRICT
                  INTO VNID_DISTRICT
                  FROM DISTRICT
                  WHERE ID_DISTRICT=PNID_DISTRICT;
                  RETURN (VNID_DISTRICT);
         END;

        -------------------------------------------------------------------------------
        --FUNCTION GET_ID_CANTON IMPLEMENTATION
        FUNCTION GET_ID_CANTON(PNID_DISTRICT IN NUMBER)  RETURN NUMBER
         IS
                  VNID_CANTON                      NUMBER(10);
         BEGIN
                  SELECT ID_CANTON
                  INTO VNID_CANTON
                  FROM DISTRICT
                  WHERE ID_DISTRICT=PNID_DISTRICT;
                  RETURN (VNID_CANTON);
         END;

        -------------------------------------------------------------------------------
        --FUNCTION GET_NAME_DISTRICT IMPLEMENTATION
        FUNCTION GET_NAME_DISTRICT(PNID_DISTRICT IN NUMBER) RETURN VARCHAR2
        IS
                 VNNAME_DISTRICT VARCHAR2(50);

        BEGIN
                  SELECT NAME_DISTRICT
                  INTO VNNAME_DISTRICT
                  FROM DISTRICT
                  WHERE ID_DISTRICT=PNID_DISTRICT;
                  RETURN (VNNAME_DISTRICT);
        END;

        PROCEDURE PROC_INSERT_DISTRICT(ID_DISTRICT NUMBER,ID_CANTON NUMBER,NAME_DISTRICT VARCHAR2) IS
         
           BEGIN
             INSERT INTO DISTRICT(ID_DISTRICT,ID_CANTON,NAME_DISTRICT)
             VALUES (ID_DISTRICT,ID_CANTON,NAME_DISTRICT);
             
           END PROC_INSERT_DISTRICT;
           
        ---------------------------------------------------------------------------------
        PROCEDURE SET_ID_DISTRICT(NEW_VALUE NUMBER, OLD_VALUE NUMBER) IS
         BEGIN
             UPDATE DISTRICT SET ID_DISTRICT= NEW_VALUE WHERE ID_DISTRICT=OLD_VALUE;             
         END SET_ID_DISTRICT;
         
         
         ---------------------------------------------------------------------------------
         PROCEDURE SET_ID_CANTON(NEW_VALUE NUMBER, OLD_VALUE NUMBER) IS
         BEGIN
             UPDATE DISTRICT SET ID_CANTON= NEW_VALUE WHERE ID_CANTON=OLD_VALUE;             
         END SET_ID_CANTON;
         
         
         ---------------------------------------------------------------------------------
         PROCEDURE SET_NAME_DISTRICT(NEW_VALUE VARCHAR2, OLD_VALUE VARCHAR2) IS
         BEGIN
             UPDATE DISTRICT SET NAME_DISTRICT= NEW_VALUE WHERE NAME_DISTRICT=OLD_VALUE;             
         END SET_NAME_DISTRICT;
END PKG_ADMIN_DISTRICT;
