CREATE OR REPLACE PACKAGE PKG_ADMIN_CATEGORY_FAV  IS
       FUNCTION GET_ID_CATEGORY_FAV(PNID_CATEGORY_FAV IN NUMBER)  RETURN NUMBER;
       FUNCTION GET_NAME_CATEGORY(PNID_CATEGORY_FAV IN NUMBER)  RETURN VARCHAR2;
       PROCEDURE PROC_INSERT_CATEGORY_FAV(ID_CATEGORY_FAV NUMBER, NAME_CATEGORY VARCHAR2);
       PROCEDURE SET_ID_CATEGORY_FAV(NEW_VALUE NUMBER, OLD_VALUE NUMBER);
       PROCEDURE SET_NAME_CATEGORY(NEW_VALUE VARCHAR2, OLD_VALUE VARCHAR2);
END PKG_ADMIN_CATEGORY_FAV;

CREATE OR REPLACE PACKAGE BODY PKG_ADMIN_CATEGORY_FAV IS
        --FUNCTION GET_ID_CATEGORY_FAV IMPLEMENTATION
        FUNCTION GET_ID_CATEGORY_FAV(PNID_CATEGORY_FAV IN NUMBER)  RETURN NUMBER
         IS
                  VNID_CATEGORY_FAV                        NUMBER(10);
         BEGIN
                  SELECT ID_CATEGORY_FAV
                  INTO VNID_CATEGORY_FAV
                  FROM CATEGORY_FAV
                  WHERE ID_CATEGORY_FAV=PNID_CATEGORY_FAV;
                  RETURN (VNID_CATEGORY_FAV);
         END;

        -------------------------------------------------------------------------------
        --FUNCTION GET_NAME_CATEGORY IMPLEMENTATION
        FUNCTION GET_NAME_CATEGORY(PNID_CATEGORY_FAV IN NUMBER) RETURN VARCHAR2
        IS
                 VNNAME_CATEGORY_FAV VARCHAR2(50);

        BEGIN
                  SELECT NAME_CATEGORY
                  INTO VNNAME_CATEGORY_FAV
                  FROM CATEGORY_FAV
                  WHERE ID_CATEGORY_FAV=PNID_CATEGORY_FAV;
                  RETURN (VNNAME_CATEGORY_FAV);
        END;
        
        PROCEDURE PROC_INSERT_CATEGORY_FAV(ID_CATEGORY_FAV NUMBER, NAME_CATEGORY VARCHAR2) IS
         
           BEGIN
             INSERT INTO CATEGORY_FAV(ID_CATEGORY_FAV, NAME_CATEGORY)
             VALUES (ID_CATEGORY_FAV, NAME_CATEGORY);
             
           END PROC_INSERT_CATEGORY_FAV;
           
           
       PROCEDURE SET_ID_CATEGORY_FAV(NEW_VALUE NUMBER, OLD_VALUE NUMBER) IS
           BEGIN
               UPDATE CATEGORY_FAV SET ID_CATEGORY_FAV= NEW_VALUE WHERE ID_CATEGORY_FAV=OLD_VALUE;            
           END SET_ID_CATEGORY_FAV;
         
       PROCEDURE SET_NAME_CATEGORY(NEW_VALUE VARCHAR2, OLD_VALUE VARCHAR2) IS
           BEGIN
               UPDATE CATEGORY_FAV SET NAME_CATEGORY= NEW_VALUE WHERE NAME_CATEGORY=OLD_VALUE;            
           END SET_NAME_CATEGORY;


END PKG_ADMIN_CATEGORY_FAV;
