--PROPOSAL_X_CATEGORY_ADMINISTRATOR PACKAGE IMPLEMENTATION
CREATE OR REPLACE PACKAGE PKG_ADMIN_PROPOSAL_X_CATEGORY IS
       FUNCTION GET_ID_CATEGORY_FAV(PNID_PROPOSAL IN NUMBER)  RETURN NUMBER;
       FUNCTION GET_ID_PROPOSAL(PNID_PROPOSAL IN NUMBER)  RETURN NUMBER;

END PKG_ADMIN_PROPOSAL_X_CATEGORY;

CREATE OR REPLACE PACKAGE BODY PKG_ADMIN_PROPOSAL_X_CATEGORY IS
        --FUNCTION GET_ID_PERSON IMPLEMENTATION
        FUNCTION GET_ID_CATEGORY_FAV(PNID_PROPOSAL IN NUMBER)  RETURN NUMBER
         IS
                  VNID_CATEGORY_FAV                     NUMBER(10);
         BEGIN
                  SELECT ID_CATEGORY_FAV  
                  INTO VNID_CATEGORY_FAV
                  FROM PROPOSAL_X_CATEGORY
                  WHERE ID_PROPOSAL=PNID_PROPOSAL;
                  RETURN (VNID_CATEGORY_FAV);
         END;

        -------------------------------------------------------------------------------
        --FUNCTION GET_ID_CATEGORY IMPLEMENTATION
        FUNCTION GET_ID_PROPOSAL(PNID_PROPOSAL IN NUMBER) RETURN NUMBER
        IS
                 VNID_PROPOSAL NUMBER(20);

        BEGIN
                  SELECT ID_PROPORSAL
                  INTO VNID_PROPOSAL
                  FROM PROPOSAL_X_CATEGORY
                  WHERE ID_PROPORSAL=PNID_PROPOSAL;
                  RETURN (VNID_PROPOSAL);
        END;
       
END PKG_ADMIN_PROPOSAL_X_CATEGORY;
