CREATE OR REPLACE PACKAGE PKG_ADMIN_COUNTRY  IS
       FUNCTION GET_ID_COUNTRY(PNID_COUNTRY IN NUMBER)  RETURN NUMBER;
       FUNCTION GET_NAME_COUNTRY(PNID_COUNTRY IN NUMBER)  RETURN VARCHAR2;
       PROCEDURE PROC_INSERT_COUNTRY(ID_COUNTRY NUMBER, NAME_COUNTRY VARCHAR2);
       PROCEDURE SET_ID_COUNTRY(NEW_VALUE NUMBER, OLD_VALUE NUMBER);
       PROCEDURE SET_NAME_COUNTRY(NEW_VALUE VARCHAR2, OLD_VALUE VARCHAR2);
END PKG_ADMIN_COUNTRY;


CREATE OR REPLACE PACKAGE BODY PKG_ADMIN_COUNTRY IS
        --FUNCTION GET_ID_COUNTRY IMPLEMENTATION
        FUNCTION GET_ID_COUNTRY(PNID_COUNTRY IN NUMBER)  RETURN NUMBER
         IS
                  VNID_COUNTRY                      NUMBER(10);
         BEGIN
                  SELECT ID_COUNTRY
                  INTO VNID_COUNTRY
                  FROM COUNTRY
                  WHERE ID_COUNTRY=PNID_COUNTRY;
                  RETURN (VNID_COUNTRY);
         END;

        -------------------------------------------------------------------------------
        --FUNCTION GET_NAME_COUNTRY IMPLEMENTATION
        FUNCTION GET_NAME_COUNTRY(PNID_COUNTRY IN NUMBER) RETURN VARCHAR2
        IS
                 VNNAME_COUNTRY VARCHAR2(50);

        BEGIN
                  SELECT NAME_COUNTRY
                  INTO VNNAME_COUNTRY
                  FROM COUNTRY
                  WHERE ID_COUNTRY=PNID_COUNTRY;
                  RETURN (VNNAME_COUNTRY);
        END;

        PROCEDURE PROC_INSERT_COUNTRY(ID_COUNTRY NUMBER, NAME_COUNTRY VARCHAR2) IS
         
           BEGIN
             INSERT INTO COUNTRY(ID_COUNTRY, NAME_COUNTRY)
             VALUES (ID_COUNTRY, NAME_COUNTRY);
             
           END PROC_INSERT_COUNTRY;
           
       ---------------------------------------------------------------------------------
       PROCEDURE SET_ID_COUNTRY(NEW_VALUE NUMBER, OLD_VALUE NUMBER) IS
         BEGIN
             UPDATE COUNTRY SET ID_COUNTRY= NEW_VALUE WHERE ID_COUNTRY=OLD_VALUE;            
         END SET_ID_COUNTRY;
         
         
       ---------------------------------------------------------------------------------
       PROCEDURE SET_NAME_COUNTRY(NEW_VALUE VARCHAR2, OLD_VALUE VARCHAR2) IS
         BEGIN
             UPDATE COUNTRY SET NAME_COUNTRY= NEW_VALUE WHERE NAME_COUNTRY=OLD_VALUE;            
         END SET_NAME_COUNTRY;

END PKG_ADMIN_COUNTRY;
