CREATE OR REPLACE PACKAGE PKG_ADMIN_CATEGORY  IS
       FUNCTION GET_ID_CATEGORY(PNCATEGORY_NAME IN VARCHAR2)  RETURN NUMBER;
       FUNCTION GET_CATEGORY_NAME(PNID_CATEGORY IN NUMBER)  RETURN VARCHAR2;
       PROCEDURE INSERT_CATEGORY(PNCATEGORY_NAME VARCHAR2);
       --PROCEDURE SET_ID_CATEGORY(PNNEW_VALUE NUMBER, PNOLD_VALUE NUMBER);
       PROCEDURE SET_CATEGORY_NAME(PNID_CATEGORY NUMBER, PNNEW_VALUE VARCHAR2);
END PKG_ADMIN_CATEGORY;


CREATE OR REPLACE PACKAGE BODY PKG_ADMIN_CATEGORY IS
        --FUNCTION GET_ID_CATEGORY IMPLEMENTATION
        FUNCTION GET_ID_CATEGORY(PNCATEGORY_NAME IN VARCHAR2)  RETURN NUMBER
         IS
                 VMENERROR      EXCEPTION;
                  VNID_CATEGORY  NUMBER(10);
         BEGIN
                  SELECT ID_CATEGORY
                  INTO VNID_CATEGORY
                  FROM CATEGORY
                  WHERE CATEGORY_NAME=PNCATEGORY_NAME;
                  RETURN (VNID_CATEGORY);
                 EXCEPTION 
                         WHEN TOO_MANY_ROWS THEN
                           DBMS_OUTPUT.PUT_LINE('YOUR SELECTION RETURNS MORE THAN ONE RESULT.');
                         WHEN NO_DATA_FOUND THEN
                           DBMS_OUTPUT.PUT_LINE('THE ELEMENT DOES NOT EXIST IN THE DATABASE.');
                         WHEN OTHERS THEN
                           DBMS_OUTPUT.PUT_LINE('ERROR');
                  
         END;

        -------------------------------------------------------------------------------
        --FUNCTION GET_CATEGORY_NAME IMPLEMENTATION
        FUNCTION GET_CATEGORY_NAME(PNID_CATEGORY IN NUMBER) RETURN VARCHAR2
        IS
                 VMENERROR      EXCEPTION;
                 VNCATEGORY_NAME VARCHAR2(50);

        BEGIN
                  SELECT CATEGORY_NAME
                  INTO VNCATEGORY_NAME
                  FROM CATEGORY
                  WHERE ID_CATEGORY=PNID_CATEGORY;
                  RETURN (VNCATEGORY_NAME);
                 EXCEPTION 
                         WHEN TOO_MANY_ROWS THEN
                           DBMS_OUTPUT.PUT_LINE('YOUR SELECTION RETURNS MORE THAN ONE RESULT.');
                         WHEN NO_DATA_FOUND THEN
                           DBMS_OUTPUT.PUT_LINE('THE ELEMENT DOES NOT EXIST IN THE DATABASE.');
                         WHEN OTHERS THEN
                           DBMS_OUTPUT.PUT_LINE('ERROR');
        END;

        PROCEDURE INSERT_CATEGORY(PNCATEGORY_NAME VARCHAR2) IS

           BEGIN
             INSERT INTO CATEGORY(ID_CATEGORY, CATEGORY_NAME)
             VALUES (S_CATEGORY.NEXTVAL, PNCATEGORY_NAME);

           END INSERT_CATEGORY;


       --PROCEDURE SET_ID_CATEGORY(PNNEW_VALUE NUMBER, PNOLD_VALUE NUMBER) IS
       --    BEGIN
       --        UPDATE CATEGORY SET ID_CATEGORY= PNNEW_VALUE WHERE ID_CATEGORY=PNOLD_VALUE;
       --    END SET_ID_CATEGORY;

       PROCEDURE SET_CATEGORY_NAME(PNID_CATEGORY NUMBER, PNNEW_VALUE VARCHAR2) IS
         VMENERROR                               EXCEPTION;
           BEGIN
               UPDATE CATEGORY SET CATEGORY_NAME= PNNEW_VALUE WHERE ID_CATEGORY=PNID_CATEGORY;
               IF SQL%NOTFOUND THEN
                    RAISE VMENERROR;
            END IF;
            EXCEPTION 
               WHEN VMENERROR THEN
                 DBMS_OUTPUT.PUT_LINE('THE ELEMENT DOES NOT EXIST IN THE DATABASE.');
           END SET_CATEGORY_NAME;


END PKG_ADMIN_CATEGORY;
