CREATE OR REPLACE PACKAGE PKG_ADMIN_KIND_PERSON  IS
       FUNCTION GET_ID_USERTYPE(PNUSERTYPE_NAME IN VARCHAR2)  RETURN NUMBER;
       --FUNCTION GET_ID_PERSON(PNID_USERTYPE IN NUMBER)  RETURN NUMBER;
       FUNCTION GET_USERTYPE_NAME(PNID_USERTYPE IN NUMBER)  RETURN VARCHAR2;
       PROCEDURE INSERT_KIND_PERSON(PNUSERTYPE_NAME VARCHAR2);
       --PROCEDURE SET_ID_USERTYPE(PNNEW_VALUE NUMBER, PNOLD_VALUE NUMBER);
       --PROCEDURE SET_ID_PERSON(PNNEW_VALUE NUMBER, PNOLD_VALUE NUMBER);
       PROCEDURE SET_USERTYPE_NAME(PNNEW_VALUE VARCHAR2, PNOLD_VALUE VARCHAR2);
END PKG_ADMIN_KIND_PERSON;


CREATE OR REPLACE PACKAGE BODY PKG_ADMIN_KIND_PERSON IS
        --FUNCTION GET_ID_USERTYPE IMPLEMENTATION
        FUNCTION GET_ID_USERTYPE(PNUSERTYPE_NAME IN VARCHAR2)  RETURN NUMBER
         IS
                 VMENERROR      EXCEPTION;
                  VNID_USERTYPE        NUMBER(10);
         BEGIN
                  SELECT ID_USERTYPE
                  INTO VNID_USERTYPE
                  FROM USERTYPE
                  WHERE USERTYPE_NAME=PNUSERTYPE_NAME;
                  RETURN (VNID_USERTYPE);
                 EXCEPTION 
                         WHEN TOO_MANY_ROWS THEN
                           DBMS_OUTPUT.PUT_LINE('YOUR SELECTION RETURNS MORE THAN ONE RESULT.');
                         WHEN NO_DATA_FOUND THEN
                           DBMS_OUTPUT.PUT_LINE('THE ELEMENT DOES NOT EXIST IN THE DATABASE.');
                         WHEN OTHERS THEN
                           DBMS_OUTPUT.PUT_LINE('ERROR');
         END;

        -------------------------------------------------------------------------------
        --FUNCTION GET_ID_PERSON IMPLEMENTATION
        --FUNCTION GET_ID_PERSON(PNID_USERTYPE IN NUMBER)  RETURN NUMBER
        -- IS
        --          VNID_PERSON                    NUMBER(10);
        -- BEGIN
        --          SELECT ID_PERSON
        --          INTO VNID_PERSON
        --          FROM KIND_PERSON
        --          WHERE ID_USERTYPE=PNID_USERTYPE;
        --          RETURN (VNID_PERSON);
        -- END;

        -------------------------------------------------------------------------------
        --FUNCTION GET_USERTYPE_NAME IMPLEMENTATION
        FUNCTION GET_USERTYPE_NAME(PNID_USERTYPE IN NUMBER) RETURN VARCHAR2
        IS
                 VMENERROR      EXCEPTION;
                 VNUSERTYPE_NAME VARCHAR(30);

        BEGIN
                  SELECT USERTYPE_NAME
                  INTO VNUSERTYPE_NAME
                  FROM USERTYPE
                  WHERE ID_USERTYPE=PNID_USERTYPE;
                  RETURN (VNUSERTYPE_NAME);
                 EXCEPTION 
                         WHEN TOO_MANY_ROWS THEN
                           DBMS_OUTPUT.PUT_LINE('YOUR SELECTION RETURNS MORE THAN ONE RESULT.');
                         WHEN NO_DATA_FOUND THEN
                           DBMS_OUTPUT.PUT_LINE('THE ELEMENT DOES NOT EXIST IN THE DATABASE.');
                         WHEN OTHERS THEN
                           DBMS_OUTPUT.PUT_LINE('ERROR');
        END;

        PROCEDURE INSERT_KIND_PERSON(PNUSERTYPE_NAME VARCHAR2) IS

           BEGIN
             INSERT INTO USERTYPE(ID_USERTYPE,USERTYPE_NAME)
             VALUES (S_USERTYPE.NEXTVAL,PNUSERTYPE_NAME);

           END INSERT_KIND_PERSON;


        ---------------------------------------------------------------------------------
    --PROCEDURE SET_ID_USERTYPE(PNNEW_VALUE NUMBER, PNOLD_VALUE NUMBER) IS
    --     BEGIN
    --         UPDATE USERTYPE SET ID_USERTYPE= PNNEW_VALUE WHERE ID_USERTYPE=PNOLD_VALUE;
    --     END SET_ID_USERTYPE;


         ---------------------------------------------------------------------------------
    --PROCEDURE SET_ID_PERSON(PNNEW_VALUE NUMBER, PNOLD_VALUE NUMBER) IS
    --     BEGIN
    --         UPDATE USERTYPE SET ID_PERSON= PNNEW_VALUE WHERE ID_PERSON=PNOLD_VALUE;

    PROCEDURE SET_USERTYPE_NAME(PNNEW_VALUE VARCHAR2, PNOLD_VALUE VARCHAR2) IS
      VMENERROR                             EXCEPTION;
         BEGIN
            UPDATE USERTYPE SET USERTYPE_NAME= PNNEW_VALUE WHERE USERTYPE_NAME=PNOLD_VALUE;
            IF SQL%NOTFOUND THEN
                    RAISE VMENERROR;
            END IF;
            EXCEPTION 
               WHEN VMENERROR THEN
                 DBMS_OUTPUT.PUT_LINE('THE ELEMENT DOES NOT EXIST IN THE DATABASE.');
         END SET_USERTYPE_NAME;


END PKG_ADMIN_KIND_PERSON;
