CREATE OR REPLACE PACKAGE PKG_ADMIN_NATIONALITY  IS
       FUNCTION GET_ID_NATIONALITY(PNID_NATIONALITY IN NUMBER)  RETURN NUMBER;
       FUNCTION GET_NAME_NATIONALITY(PNID_NATIONALITY IN NUMBER)  RETURN VARCHAR2;
       PROCEDURE PROC_INSERT_NATIONALITY(ID_NATIONALITY NUMBER, NAME_NATIONALITY VARCHAR2);
       PROCEDURE SET_ID_NATIONALITY(NEW_VALUE NUMBER, OLD_VALUE NUMBER);
       PROCEDURE SET_NAME_NATIONALITY(NEW_VALUE VARCHAR2, OLD_VALUE VARCHAR2);
END PKG_ADMIN_NATIONALITY;


CREATE OR REPLACE PACKAGE BODY PKG_ADMIN_NATIONALITY IS
        --FUNCTION GET_ID_NATIONALITY IMPLEMENTATION
        FUNCTION GET_ID_NATIONALITY(PNID_NATIONALITY IN NUMBER)  RETURN NUMBER
         IS
                  VNID_NATIONALITY                      NUMBER(10);
         BEGIN
                  SELECT ID_NATIONALITY
                  INTO VNID_NATIONALITY
                  FROM NATIONALITY
                  WHERE ID_NATIONALITY=PNID_NATIONALITY;
                  RETURN (VNID_NATIONALITY);
         END;

        -------------------------------------------------------------------------------
        --FUNCTION GET_NAME_NATIONALITY IMPLEMENTATION
        FUNCTION GET_NAME_NATIONALITY(PNID_NATIONALITY IN NUMBER) RETURN VARCHAR2
        IS
                 VNNAME_NATIONALITY VARCHAR(20);

        BEGIN
                  SELECT NAME_NATIONALITY
                  INTO VNNAME_NATIONALITY
                  FROM NATIONALITY
                  WHERE ID_NATIONALITY=PNID_NATIONALITY;
                  RETURN (VNNAME_NATIONALITY);
        END;

        PROCEDURE PROC_INSERT_NATIONALITY(ID_NATIONALITY NUMBER, NAME_NATIONALITY VARCHAR2) IS
         
           BEGIN
             INSERT INTO NATIONALITY(ID_NATIONALITY, NAME_NATIONALITY)
             VALUES (ID_NATIONALITY, NAME_NATIONALITY);
             
           END PROC_INSERT_NATIONALITY;
           
           
           ---------------------------------------------------------------------------------
    PROCEDURE SET_ID_NATIONALITY(NEW_VALUE NUMBER, OLD_VALUE NUMBER) IS
         BEGIN
             UPDATE NATIONALITY SET ID_NATIONALITY= NEW_VALUE WHERE ID_NATIONALITY=OLD_VALUE;            
         END SET_ID_NATIONALITY;
         
         
         ---------------------------------------------------------------------------------
    PROCEDURE SET_NAME_NATIONALITY(NEW_VALUE VARCHAR2, OLD_VALUE VARCHAR2) IS
         BEGIN
            UPDATE NATIONALITY SET NAME_NATIONALITY= NEW_VALUE WHERE NAME_NATIONALITY=OLD_VALUE;            
         END SET_NAME_NATIONALITY;
END PKG_ADMIN_NATIONALITY;
