--COUNTRY_ADMINISTRATOR PACKAGE IMPLEMENTATION
CREATE OR REPLACE PACKAGE PKG_ADMIN_COUNTRY  IS
       FUNCTION GET_ID_COUNTRY(PNID_COUNTRY IN NUMBER)  RETURN NUMBER;
       FUNCTION GET_NAME_COUNTRY(PNID_COUNTRY IN NUMBER)  RETURN VARCHAR2;
END PKG_ADMIN_COUNTRY;

CREATE OR REPLACE PACKAGE BODY PKG_ADMIN_COUNTRY IS
        --FUNCTION GET_ID_PERSON IMPLEMENTATION
        FUNCTION GET_ID_COMMUNITY(PNID_COUNTRY IN NUMBER)  RETURN NUMBER
         IS
                  VNID_COUNTRY                      NUMBER(10);
         BEGIN
                  SELECT ID_COUNTRY   
                  INTO VNID_COUNTRY
                  FROM COUNTRY
                  WHERE ID_COUNTRY=PNID_COUNTRY;
                  RETURN (VNID_COUNTRY);
         END;
         
        -------------------------------------------------------------------------------
        --FUNCTION GET_ID_CATEGORY IMPLEMENTATION
        FUNCTION GET_NAME_COUNTRY(PNID_COUNTRY IN NUMBER) RETURN VARCHAR2
        IS
                 VNNAME_COUNTRY DATE;

        BEGIN
                  SELECT NAME_COUNTRY
                  INTO VNNAME_COUNTRY
                  FROM COUNTRY
                  WHERE ID_COUNTRY=PNID_COUNTRY;
                  RETURN (VNNAME_COUNTRY);
        END;

       
END PKG_ADMIN_COUNTRY;
