CREATE OR REPLACE PACKAGE PKG_ADMIN_CANTON IS
       FUNCTION GET_ID_CANTON(PNID_CANTON IN NUMBER)  RETURN NUMBER;
       FUNCTION GET_ID_PROVINCE(PNID_CANTON IN NUMBER)  RETURN NUMBER;
       FUNCTION GET_NAME_CANTON(PNID_CANTON IN NUMBER)  RETURN VARCHAR2;
       PROCEDURE PROC_INSERT_CANTON(ID_CANTON NUMBER,ID_PROVINCE NUMBER ,NAME_CANTON VARCHAR2);
       PROCEDURE SET_ID_CANTON(NEW_VALUE NUMBER, OLD_VALUE NUMBER);
       PROCEDURE SET_ID_PROVINCE(NEW_VALUE NUMBER, OLD_VALUE NUMBER);
       PROCEDURE SET_NAME_CANTON(NEW_VALUE VARCHAR2, OLD_VALUE VARCHAR2);
END PKG_ADMIN_CANTON;

CREATE OR REPLACE PACKAGE BODY PKG_ADMIN_CANTON IS
        --FUNCTION GET_ID_CANTON IMPLEMENTATION
        FUNCTION GET_ID_CANTON(PNID_CANTON IN NUMBER)  RETURN NUMBER
         IS
                  VNID_CANTON                        NUMBER(10);
         BEGIN
                  SELECT ID_CANTON
                  INTO VNID_CANTON
                  FROM CANTON
                  WHERE ID_CANTON=PNID_CANTON;
                  RETURN (VNID_CANTON);
         END;

        -------------------------------------------------------------------------------
        --FUNCTION GET_ID_PROVINCE IMPLEMENTATION
        FUNCTION GET_ID_PROVINCE(PNID_CANTON IN NUMBER)  RETURN NUMBER
         IS
                  VNID_PROVINCE                        NUMBER(10);
         BEGIN
                  SELECT ID_PROVINCE
                  INTO VNID_PROVINCE
                  FROM CANTON
                  WHERE ID_CANTON=PNID_CANTON;
                  RETURN (VNID_PROVINCE);
         END;

        -------------------------------------------------------------------------------
        --FUNCTION GET_NAME_CANTON IMPLEMENTATION
        FUNCTION GET_NAME_CANTON(PNID_CANTON IN NUMBER) RETURN VARCHAR2
        IS
                 VNNAME_CANTON VARCHAR2(50);

        BEGIN
                  SELECT NAME_CANTON
                  INTO VNNAME_CANTON
                  FROM CANTON
                  WHERE ID_CANTON=PNID_CANTON;
                  RETURN (VNNAME_CANTON);
        END;
        
        -------------------------------------------------------------------------------
        --PROCEDURE PROC_INSERT_CANTON IMPLEMENTATION
        PROCEDURE PROC_INSERT_CANTON(ID_CANTON NUMBER,ID_PROVINCE NUMBER ,NAME_CANTON VARCHAR2) IS
         
           BEGIN
             INSERT INTO CANTON(ID_CANTON,ID_PROVINCE,NAME_CANTON)
             VALUES (ID_CANTON,ID_PROVINCE,NAME_CANTON);
             
           END PROC_INSERT_CANTON;
           
        PROCEDURE SET_ID_CANTON(NEW_VALUE NUMBER, OLD_VALUE NUMBER) IS
         BEGIN
             UPDATE CANTON SET ID_CANTON= NEW_VALUE WHERE ID_CANTON=OLD_VALUE;            
         END SET_ID_CANTON;
           
           
       PROCEDURE SET_ID_PROVINCE(NEW_VALUE NUMBER, OLD_VALUE NUMBER) IS
         BEGIN
            UPDATE CANTON SET ID_PROVINCE= NEW_VALUE WHERE ID_PROVINCE=OLD_VALUE;           
         END SET_ID_PROVINCE;
         
         
       PROCEDURE SET_NAME_CANTON(NEW_VALUE VARCHAR2, OLD_VALUE VARCHAR2) IS
         BEGIN
             UPDATE CANTON SET NAME_CANTON= NEW_VALUE WHERE NAME_CANTON=OLD_VALUE;          
         END SET_NAME_CANTON;

END PKG_ADMIN_CANTON;
