--COMMUNITY_ADMINISTRATOR PACKAGE IMPLEMENTATION
CREATE OR REPLACE PACKAGE PKG_ADMIN_COMMUNITY  IS
       FUNCTION GET_ID_COMMUNITY(PNID_COMMUNITY IN NUMBER)  RETURN NUMBER;
       FUNCTION GET_ID_DISTRICT(PNID_COMMUNITY IN NUMBER)  RETURN NUMBER;
       FUNCTION GET_NAME_COMMUNITY(PNID_COMMUNITY IN NUMBER)  RETURN VARCHAR2;
END PKG_ADMIN_COMMUNITY;

CREATE OR REPLACE PACKAGE BODY PKG_ADMIN_COMMUNITY IS
        --FUNCTION GET_ID_PERSON IMPLEMENTATION
        FUNCTION GET_ID_COMMUNITY(PNID_COMMUNITY IN NUMBER)  RETURN NUMBER
         IS
                  VNID_COMMUNITY                      NUMBER(10);
         BEGIN
                  SELECT ID_COMMUNITY   
                  INTO VNID_COMMUNITY
                  FROM COMMUNITY
                  WHERE ID_COMMUNITY=PNID_COMMUNITY;
                  RETURN (VNID_COMMUNITY);
         END;
         
        -------------------------------------------------------------------------------
        --FUNCTION GET_ID_CATEGORY IMPLEMENTATION
        FUNCTION GET_ID_DISTRICT(PNID_COMMUNITY IN NUMBER) RETURN NUMBER
        IS
                 VNID_DISTRICT                NUMBER(10);

        BEGIN
                  SELECT ID_COMMUNITY
                  INTO VNID_DISTRICT
                  FROM COMMUNITY
                  WHERE ID_COMMUNITY=PNID_COMMUNITY;
                  RETURN (VNID_DISTRICT);
        END;
         
        -------------------------------------------------------------------------------
        --FUNCTION GET_ID_CATEGORY IMPLEMENTATION
        FUNCTION GET_NAME_COMMUNITY(PNID_COMMUNITY IN NUMBER) RETURN VARCHAR2
        IS
                 VNNAME_COMMUNITY DATE;

        BEGIN
                  SELECT NAME_COMMUNITY
                  INTO VNNAME_COMMUNITY
                  FROM COMMUNITY
                  WHERE ID_COMMUNITY=PNID_COMMUNITY;
                  RETURN (VNNAME_COMMUNITY);
        END;

       
END PKG_ADMIN_COMMUNITY;
