CREATE OR REPLACE PACKAGE PKG_ADMIN_USERNAME IS
       FUNCTION GET_ID_USERNAME(PNID_USERNAME IN NUMBER)  RETURN NUMBER;
       FUNCTION GET_ID_PERSON(PNID_USERNAME IN NUMBER)  RETURN NUMBER;
       FUNCTION GET_PASSWORD_USER(PNID_USERNAME IN NUMBER)  RETURN VARCHAR2;
       PROCEDURE PROC_INSERT_USERNAME(ID_USERNAME NUMBER,ID_PERSON NUMBER,PASSWORD_USER VARCHAR2);
       PROCEDURE SET_ID_USERNAME(NEW_VALUE NUMBER, OLD_VALUE NUMBER);
       PROCEDURE SET_ID_PERSON(NEW_VALUE NUMBER, OLD_VALUE NUMBER);
       PROCEDURE SET_PASSWORD_USER(NEW_VALUE VARCHAR2, OLD_VALUE VARCHAR2);
END PKG_ADMIN_USERNAME;

CREATE OR REPLACE PACKAGE BODY PKG_ADMIN_USERNAME IS
        --FUNCTION GET_ID_USERNAME IMPLEMENTATION
        FUNCTION GET_ID_USERNAME(PNID_USERNAME IN NUMBER)  RETURN NUMBER
         IS
                  VNID_USERNAME                        NUMBER(10);
         BEGIN
                  SELECT ID_USERNAME
                  INTO VNID_USERNAME
                  FROM USERNAME
                  WHERE ID_USERNAME=PNID_USERNAME;
                  RETURN (VNID_USERNAME);
         END;

        -------------------------------------------------------------------------------
        --FUNCTION GET_ID_PERSON IMPLEMENTATION
        FUNCTION GET_ID_PERSON(PNID_USERNAME IN NUMBER)  RETURN NUMBER
         IS
                  VNID_PERSON                        NUMBER(10);
         BEGIN
                  SELECT ID_PERSON
                  INTO VNID_PERSON
                  FROM USERNAME
                  WHERE ID_USERNAME=PNID_USERNAME;
                  RETURN (VNID_PERSON);
         END;

        -------------------------------------------------------------------------------
        --FUNCTION GET_PASSWORD_USER IMPLEMENTATION
        FUNCTION GET_PASSWORD_USER(PNID_USERNAME IN NUMBER) RETURN VARCHAR2
        IS
                 VNPASSWORD_USER VARCHAR2(50);

        BEGIN
                  SELECT PASSWORD_USER
                  INTO VNPASSWORD_USER
                  FROM USERNAME
                  WHERE ID_USERNAME=PNID_USERNAME;
                  RETURN (VNPASSWORD_USER);
        END;

        PROCEDURE PROC_INSERT_USERNAME(ID_USERNAME NUMBER,ID_PERSON NUMBER,PASSWORD_USER VARCHAR2) IS
         
           BEGIN
             INSERT INTO USERNAME(ID_USERNAME,ID_PERSON,PASSWORD_USER)
             VALUES (ID_USERNAME,ID_PERSON,PASSWORD_USER);
             
           END PROC_INSERT_USERNAME;
           
           ---------------------------------------------------------------------------------
    PROCEDURE SET_ID_USERNAME(NEW_VALUE NUMBER, OLD_VALUE NUMBER) IS
         BEGIN
             UPDATE USERNAME SET ID_USERNAME= NEW_VALUE WHERE ID_USERNAME=OLD_VALUE;            
         END SET_ID_USERNAME;
         
         ---------------------------------------------------------------------------------
    PROCEDURE SET_ID_PERSON(NEW_VALUE NUMBER, OLD_VALUE NUMBER) IS
         BEGIN
             UPDATE USERNAME SET ID_PERSON= NEW_VALUE WHERE ID_PERSON=OLD_VALUE;             
         END SET_ID_PERSON;
         
         ---------------------------------------------------------------------------------
    PROCEDURE SET_PASSWORD_USER(NEW_VALUE VARCHAR2, OLD_VALUE VARCHAR2) IS
         BEGIN
             UPDATE USERNAME SET PASSWORD_USER= NEW_VALUE WHERE PASSWORD_USER=OLD_VALUE;             
         END SET_PASSWORD_USER;
END PKG_ADMIN_USERNAME;
