CREATE OR REPLACE PACKAGE PKG_ADMIN_PROVINCE  IS
       FUNCTION GET_ID_PROVINCE(PNID_PROVINCE IN NUMBER)  RETURN NUMBER;
       FUNCTION GET_ID_COUNTRY(PNID_PROVINCE IN NUMBER)  RETURN NUMBER;
       FUNCTION GET_NAME_PROVINCE(PNID_PROVINCE IN NUMBER)  RETURN VARCHAR2;
       PROCEDURE PROC_INSERT_PROVINCE(ID_PROVINCE NUMBER,ID_COUNTRY NUMBER,NAME_PROVINCE VARCHAR2);
       PROCEDURE SET_ID_PROVINCE(NEW_VALUE NUMBER, OLD_VALUE NUMBER);
       PROCEDURE SET_ID_COUNTRY(NEW_VALUE NUMBER, OLD_VALUE NUMBER);
       PROCEDURE SET_NAME_PROVINCE(NEW_VALUE VARCHAR2, OLD_VALUE VARCHAR2);
END PKG_ADMIN_PROVINCE;


CREATE OR REPLACE PACKAGE BODY PKG_ADMIN_PROVINCE IS
        --FUNCTION GET_ID_PROVINCE IMPLEMENTATION
        FUNCTION GET_ID_PROVINCE(PNID_PROVINCE IN NUMBER)  RETURN NUMBER
         IS
                  VNID_PROVINCE                      NUMBER(10);
         BEGIN
                  SELECT ID_PROVINCE
                  INTO VNID_PROVINCE
                  FROM PROVINCE
                  WHERE ID_PROVINCE=PNID_PROVINCE;
                  RETURN (VNID_PROVINCE);
         END;

        -------------------------------------------------------------------------------
        --FUNCTION GET_ID_COUNTRY IMPLEMENTATION
        FUNCTION GET_ID_COUNTRY(PNID_PROVINCE IN NUMBER)  RETURN NUMBER
         IS
                  VNID_COUNTRY                    NUMBER(10);
         BEGIN
                  SELECT ID_COUNTRY
                  INTO VNID_COUNTRY
                  FROM PROVINCE
                  WHERE ID_PROVINCE=PNID_PROVINCE;
                  RETURN (VNID_COUNTRY);
         END;

        -------------------------------------------------------------------------------
        --FUNCTION GET_NAME_PROVINCE IMPLEMENTATION
        FUNCTION GET_NAME_PROVINCE(PNID_PROVINCE IN NUMBER) RETURN VARCHAR2
        IS
                 VNNAME_PROVINCE VARCHAR2(20);

        BEGIN
                  SELECT NAME_PROVINCE
                  INTO VNNAME_PROVINCE
                  FROM PROVINCE
                  WHERE ID_PROVINCE=PNID_PROVINCE;
                  RETURN (VNNAME_PROVINCE);
        END;

        PROCEDURE PROC_INSERT_PROVINCE(ID_PROVINCE NUMBER,ID_COUNTRY NUMBER,NAME_PROVINCE VARCHAR2) IS
         
           BEGIN
             INSERT INTO PROVINCE(ID_PROVINCE,ID_COUNTRY,NAME_PROVINCE)
             VALUES (ID_PROVINCE,ID_COUNTRY,NAME_PROVINCE);
             
           END PROC_INSERT_PROVINCE;
           
           
           ---------------------------------------------------------------------------------
    PROCEDURE SET_ID_PROVINCE(NEW_VALUE NUMBER, OLD_VALUE NUMBER) IS
         BEGIN
             UPDATE PROVINCE SET ID_PROVINCE= NEW_VALUE WHERE ID_PROVINCE=OLD_VALUE;            
         END SET_ID_PROVINCE;
         
         
         ---------------------------------------------------------------------------------
    PROCEDURE SET_ID_COUNTRY(NEW_VALUE NUMBER, OLD_VALUE NUMBER) IS
         BEGIN
             UPDATE PROVINCE SET ID_COUNTRY= NEW_VALUE WHERE ID_COUNTRY=OLD_VALUE;             
         END SET_ID_COUNTRY;
         
         
         ---------------------------------------------------------------------------------
    PROCEDURE SET_NAME_PROVINCE(NEW_VALUE VARCHAR2, OLD_VALUE VARCHAR2) IS
         BEGIN
             UPDATE PROVINCE SET NAME_PROVINCE= NEW_VALUE WHERE NAME_PROVINCE=OLD_VALUE;             
         END SET_NAME_PROVINCE;
END PKG_ADMIN_PROVINCE;
