CREATE OR REPLACE PACKAGE PKG_ADMIN_PERSON_X_PROPOSAL IS
       FUNCTION GET_ID_PERSON(PNID_PROPOSAL IN NUMBER)  RETURN VARCHAR2;
       --FUNCTION GET_ID_PROPOSAL(PNID_PERSON IN NUMBER)  RETURN NUMBER;
       PROCEDURE INSERT_PERSON_X_PROPOSAL(PNID_PROPOSAL NUMBER, PNID_PERSON VARCHAR2);
       --PROCEDURE SET_ID_PERSON(NEW_VALUE NUMBER, OLD_VALUE NUMBER);
       --PROCEDURE SET_ID_PROPOSAL(NEW_VALUE NUMBER, OLD_VALUE NUMBER);


END PKG_ADMIN_PERSON_X_PROPOSAL;


CREATE OR REPLACE PACKAGE BODY PKG_ADMIN_PERSON_X_PROPOSAL IS
        --FUNCTION GET_ID_PERSON IMPLEMENTATION
        FUNCTION GET_ID_PERSON(PNID_PROPOSAL IN NUMBER)  RETURN VARCHAR2
         IS
                  VMENERROR      EXCEPTION;
                  VNID_PERSON   VARCHAR2(30);
         BEGIN
                  SELECT ID_PERSON
                  INTO VNID_PERSON
                  FROM PERSON_X_PROPOSAL
                  WHERE ID_PROPOSAL=PNID_PROPOSAL;
                  RETURN (VNID_PERSON);
                  EXCEPTION 
                         WHEN TOO_MANY_ROWS THEN
                           DBMS_OUTPUT.PUT_LINE('YOUR SELECTION RETURNS MORE THAN ONE RESULT.');
                         WHEN NO_DATA_FOUND THEN
                           DBMS_OUTPUT.PUT_LINE('THE ELEMENT DOES NOT EXIST IN THE DATABASE.');
                         WHEN OTHERS THEN
                           DBMS_OUTPUT.PUT_LINE('ERROR');
         END;

        -------------------------------------------------------------------------------
        --FUNCTION GET_ID_PROPOSAL IMPLEMENTATION
        --FUNCTION GET_ID_PROPOSAL(PNID_PERSON IN NUMBER) RETURN NUMBER
        --IS
        --         VNID_PROPOSAL NUMBER(20);

        --BEGIN
        --          SELECT ID_PROPOSAL
        --          INTO VNID_PROPOSAL
        --          FROM PERSON_X_PROPOSAL
        --          WHERE ID_PERSON=PNID_PERSON;
        --         RETURN (VNID_PROPOSAL);
        --END;

        PROCEDURE INSERT_PERSON_X_PROPOSAL(PNID_PROPOSAL NUMBER, PNID_PERSON VARCHAR2) IS
      VMENERROR                                     EXCEPTION;

           BEGIN
             INSERT INTO PERSON_X_PROPOSAL(ID_PROPOSAL, ID_PERSON)
             VALUES (PNID_PROPOSAL, PNID_PERSON);
             IF SQL%NOTFOUND THEN
                    RAISE VMENERROR;
            END IF;
            EXCEPTION 
               WHEN VMENERROR THEN
                 DBMS_OUTPUT.PUT_LINE('THE ELEMENT DOES NOT EXIST IN THE DATABASE.');
               WHEN DUP_VAL_ON_INDEX THEN
                 DBMS_OUTPUT.PUT_LINE('THE ELEMENT IS ALREADY IN THE DATABASE.');

           END INSERT_PERSON_X_PROPOSAL;


           ---------------------------------------------------------------------------------
    --PROCEDURE SET_ID_PERSON(NEW_VALUE NUMBER, OLD_VALUE NUMBER) IS
    --     BEGIN
    --         UPDATE PERSON_X_PROPOSAL SET ID_PERSON= NEW_VALUE WHERE ID_PERSON=OLD_VALUE;
    --     END SET_ID_PERSON;


         ---------------------------------------------------------------------------------
    --PROCEDURE SET_ID_PROPOSAL(NEW_VALUE NUMBER, OLD_VALUE NUMBER) IS
    --     BEGIN
    --        UPDATE PERSON_X_PROPOSAL SET ID_PROPOSAL= NEW_VALUE WHERE ID_PROPOSAL=OLD_VALUE;
     --    END SET_ID_PROPOSAL;
END PKG_ADMIN_PERSON_X_PROPOSAL;
