
CREATE OR REPLACE PACKAGE PKG_ADMIN_VOTE IS
       --FUNCTION GET_ID_PERSON(PNID_PERSON IN NUMBER)  RETURN NUMBER;
       --FUNCTION GET_ID_PROPOSAL(PNID_PERSON IN NUMBER)  RETURN NUMBER;
       PROCEDURE INSERT_VOTE(PNID_PROPOSAL NUMBER, PNID_PERSON VARCHAR2);
       --PROCEDURE GET_ID_PERSON(PNNEW_VALUE NUMBER, PNOLD_VALUE NUMBER);
       --PROCEDURE GET_ID_PROPOSAL(PNNEW_VALUE NUMBER, PNOLD_VALUE NUMBER);
       PROCEDURE GET_ALL_VOTE(PRECORDSET OUT SYS_REFCURSOR, PNID_VOTE IN number default null);
END PKG_ADMIN_VOTE;


CREATE OR REPLACE PACKAGE BODY PKG_ADMIN_VOTE IS

        -------------------------------------------------------------------------------
 

        PROCEDURE INSERT_VOTE(PNID_PROPOSAL NUMBER, PNID_PERSON VARCHAR2) IS
        VMENERROR        EXCEPTION;
           BEGIN
             INSERT INTO VOTE(ID_PROPOSAL, ID_PERSON)
             VALUES (PNID_PROPOSAL, PNID_PERSON);
             UPDATE PROPOSAL SET VOTE= ((SELECT VOTE FROM PROPOSAL WHERE ID_PROPOSAL=PNID_PROPOSAL)+1)
                    WHERE ID_PROPOSAL=PNID_PROPOSAL;
                    
            IF SQL%NOTFOUND THEN
                    RAISE VMENERROR;
            END IF;
            EXCEPTION 
               WHEN VMENERROR THEN
                 DBMS_OUTPUT.PUT_LINE('THE ELEMENT DOES NOT EXIST IN THE DATABASE.');
               WHEN DUP_VAL_ON_INDEX THEN
                 DBMS_OUTPUT.PUT_LINE('THE ELEMENT IS ALREADY IN THE DATABASE.');

           END INSERT_VOTE;

           ---------------------------------------------------------------------------------
    
    
      PROCEDURE GET_ALL_VOTE(PRECORDSET OUT SYS_REFCURSOR, PNID_VOTE IN number default null) AS
                VMENERROR        EXCEPTION;
       BEGIN
              OPEN pRecordSet FOR
              SELECT ID_PROPOSAL,ID_PERSON
              FROM VOTE
              WHERE ID_PROPOSAL = NVL(PNID_VOTE, ID_PROPOSAL);
              
            IF SQL%NOTFOUND THEN
                    RAISE VMENERROR;
            END IF;
            EXCEPTION 
               WHEN VMENERROR THEN
                 DBMS_OUTPUT.PUT_LINE('THE ELEMENT DOES NOT EXIST IN THE DATABASE.');
               WHEN DUP_VAL_ON_INDEX THEN
                 DBMS_OUTPUT.PUT_LINE('THE ELEMENT IS ALREADY IN THE DATABASE.');
          END GET_ALL_VOTE;
END PKG_ADMIN_VOTE;

