CREATE OR REPLACE PACKAGE PKG_ADMIN_CANTON IS
       FUNCTION GET_ID_CANTON(PNCANTON_NAME IN VARCHAR2)  RETURN NUMBER;
       FUNCTION GET_ID_PROVINCE(PNID_CANTON IN NUMBER)  RETURN NUMBER;
       FUNCTION GET_NAME_CANTON(PNID_CANTON IN NUMBER)  RETURN VARCHAR2;
       PROCEDURE INSERT_CANTON(PNCANTON_NAME VARCHAR2,PNID_PROVINCE NUMBER);
       --PROCEDURE SET_ID_CANTON(PNNEW_VALUE NUMBER, PNOLD_VALUE NUMBER);
       PROCEDURE SET_ID_PROVINCE(PNNEW_VALUE NUMBER, PNOLD_VALUE NUMBER);
       PROCEDURE SET_NAME_CANTON(PNNEW_VALUE VARCHAR2, PNOLD_VALUE VARCHAR2);
END PKG_ADMIN_CANTON;

CREATE OR REPLACE PACKAGE BODY PKG_ADMIN_CANTON IS
        --FUNCTION GET_ID_CANTON IMPLEMENTATION
        FUNCTION GET_ID_CANTON(PNCANTON_NAME IN VARCHAR2)  RETURN NUMBER
         IS
                  VNID_CANTON    NUMBER(10);
         BEGIN
                  SELECT ID_CANTON
                  INTO VNID_CANTON
                  FROM CANTON
                  WHERE CANTON_NAME=PNCANTON_NAME;
                  RETURN (VNID_CANTON);
         END;

        -------------------------------------------------------------------------------
        --FUNCTION GET_ID_PROVINCE IMPLEMENTATION
        FUNCTION GET_ID_PROVINCE(PNID_CANTON IN NUMBER)  RETURN NUMBER
         IS
                  VNID_PROVINCE    NUMBER(10);
         BEGIN
                  SELECT ID_PROVINCE
                  INTO VNID_PROVINCE
                  FROM CANTON
                  WHERE ID_CANTON=PNID_CANTON;
                  RETURN (VNID_PROVINCE);
         END;

        -------------------------------------------------------------------------------
        --FUNCTION GET_NAME_CANTON IMPLEMENTATION
        FUNCTION GET_NAME_CANTON(PNID_CANTON IN NUMBER) RETURN VARCHAR2
        IS
                 VNNAME_CANTON VARCHAR2(50);

        BEGIN
                  SELECT CANTON_NAME
                  INTO VNNAME_CANTON
                  FROM CANTON
                  WHERE ID_CANTON=PNID_CANTON;
                  RETURN (VNNAME_CANTON);
        END;
        
        -------------------------------------------------------------------------------
        --PROCEDURE PROC_INSERT_CANTON IMPLEMENTATION
        PROCEDURE INSERT_CANTON(PNCANTON_NAME VARCHAR2, PNID_PROVINCE NUMBER) IS
         
           BEGIN
             INSERT INTO CANTON(ID_CANTON,CANTON_NAME,ID_PROVINCE)
             VALUES (S_CANTON.NEXTVAL,PNCANTON_NAME,PNID_PROVINCE);
             
           END INSERT_CANTON;
           
           
        --PROCEDURE SET_ID_CANTON(PNNEW_VALUE NUMBER, PNOLD_VALUE NUMBER) IS
        -- BEGIN
        --     UPDATE CANTON SET ID_CANTON= PNNEW_VALUE WHERE ID_CANTON=PNOLD_VALUE;            
        -- END SET_ID_CANTON;
           
           
       PROCEDURE SET_ID_PROVINCE(PNNEW_VALUE NUMBER, PNOLD_VALUE NUMBER) IS
         BEGIN
            UPDATE CANTON SET ID_PROVINCE= PNNEW_VALUE WHERE ID_PROVINCE=PNOLD_VALUE;           
         END SET_ID_PROVINCE;
         
         
       PROCEDURE SET_NAME_CANTON(PNNEW_VALUE VARCHAR2, PNOLD_VALUE VARCHAR2) IS
         BEGIN
             UPDATE CANTON SET CANTON_NAME= PNNEW_VALUE WHERE CANTON_NAME=PNOLD_VALUE;          
         END SET_NAME_CANTON;

END PKG_ADMIN_CANTON;
